name: Create Production Builds

on:
    push:
        branches: [main]

    workflow_dispatch: {}

jobs:
    build_ios:
        type: build
        params:
            platform: ios
            profile: production
