export const tinybirdPipes = [
	"list_traces",
	"span_hierarchy",
	"list_logs",
	"logs_count",
	"logs_facets",
	"error_rate_by_service",
	"get_service_usage",
	"get_service_usage_compare",
	"list_metrics",
	"metrics_summary",
	"traces_facets",
	"traces_duration_stats",
	"service_overview",
	"service_overview_compare",
	"services_facets",
	"service_releases_timeline",
	"errors_by_type",
	"error_detail_traces",
	"errors_facets",
	"errors_summary",
	"errors_timeseries",
	"error_issues",
	"error_issue_timeseries",
	"error_issue_sample_traces",
	"service_apdex_time_series",
	"alert_traces_aggregate",
	"alert_metrics_aggregate",
	"alert_logs_aggregate",
	"alert_traces_aggregate_by_service",
	"alert_metrics_aggregate_by_service",
	"alert_logs_aggregate_by_service",
	"custom_traces_timeseries",
	"custom_traces_breakdown",
	"service_dependencies",
	"metric_attribute_keys",
	"span_attribute_keys",
	"span_attribute_values",
	"resource_attribute_keys",
	"resource_attribute_values",
] as const

export type TinybirdPipe = (typeof tinybirdPipes)[number]
