
// Auto-generated by flue (target: cloudflare)
import { getPackagedSkills } from 'virtual:flue/packaged-skills';
import { env } from 'cloudflare:workers';
import { Agent, getAgentByName } from 'agents';
import {
  Bash,
  InMemoryFs,
  createFlueContext,
  createSqlRunStore,
  CLOUDFLARE_AGENT_INTERNAL_DISPATCH_PATH,
  createCloudflareAgentRuntime,
  createSqlSessionStore,
   SqliteEventStreamStore,
  bashFactoryToSessionEnv,
  resolveModel,
  handleWorkflowRequest,
  handleRunRouteRequest,
  handleStreamRead,
  handleStreamHead,
  failRecoveredRun,
  configureFlueRuntime,
  createDefaultFlueApp,
  hasRegisteredProvider,
} from '@flue/runtime/internal';
import {
  runWithCloudflareContext,
  getCloudflareAIBindingApiProvider,
  FlueRegistry,
  createCloudflareRunIndex,
  createCloudflareRunStore,
  resolveCloudflareExtension,
} from '@flue/runtime/cloudflare/internal';
import { registerApiProvider, registerProvider } from '@flue/runtime';

import * as handler_maple_chat_0 from "/Users/makisuo/Documents/GitHub/maple/apps/chat-flue/src/agents/maple-chat.ts";
import * as workflow_triage_0 from "/Users/makisuo/Documents/GitHub/maple/apps/chat-flue/src/workflows/triage.ts";

import userApp from "/Users/makisuo/Documents/GitHub/maple/apps/chat-flue/src/app.ts";



// ─── Internal provider registrations ────────────────────────────────────────
// User `app.ts` imports are hoisted above this body, so a user-supplied
// `registerProvider('cloudflare', ...)` runs first; the guard below
// preserves it. The runtime routes registrations without an explicit
// `gateway` through Cloudflare's default AI Gateway.

registerApiProvider(getCloudflareAIBindingApiProvider());

if (!hasRegisteredProvider('cloudflare')) {
  registerProvider('cloudflare', {
    api: 'cloudflare-ai-binding',
    binding: env.AI,
  });
}

// ─── Config ─────────────────────────────────────────────────────────────────

const packagedSkills = getPackagedSkills();


function normalizeBuiltModules(agentModules, workflowModules, channelModules = {}) {
  const manifest = { agents: [], workflows: [] };
  const createdAgents = {};
  const dispatchAgentNames = new Map();
  const workflowHandlers = {};
  const localWorkflowHandlers = {};
  const agentRouteMiddleware = {};
  const workflowRouteMiddleware = {};
  const channelHandlers = {};
  for (const [name, mod] of Object.entries(agentModules)) {
    if (!mod.default || mod.default.__flueCreatedAgent !== true || typeof mod.default.initialize !== 'function') throw new Error('[flue] Agent "' + name + '" must default-export createAgent(...).');
    if (mod.route !== undefined && typeof mod.route !== 'function') throw new Error('[flue] Agent "' + name + '" route export must be a callable Hono middleware value.');
    if (mod.description !== undefined && (typeof mod.description !== 'string' || mod.description.trim().length === 0)) throw new Error('[flue] Agent "' + name + '" description export must be a non-empty string.');
    const transports = {};
    if (typeof mod.route === 'function') transports.http = true;
    const entry = { name, transports, created: true };
    if (mod.description !== undefined) entry.description = mod.description;
    manifest.agents.push(entry);
    createdAgents[name] = mod.default;
    const previousDispatchName = dispatchAgentNames.get(mod.default);
    if (previousDispatchName !== undefined) throw new Error('[flue] Agents "' + previousDispatchName + '" and "' + name + '" default-export the same created agent value. Use distinct createAgent(...) values for dispatchable agent modules.');
    dispatchAgentNames.set(mod.default, name);
    if (typeof mod.route === 'function') agentRouteMiddleware[name] = mod.route;
  }

  for (const [name, mod] of Object.entries(workflowModules)) {
    if (typeof mod.run !== 'function') throw new Error('[flue] Workflow "' + name + '" must export a callable run value.');
    if (mod.route !== undefined && typeof mod.route !== 'function') throw new Error('[flue] Workflow "' + name + '" route export must be a callable Hono middleware value.');
    const transports = {};
    if (typeof mod.route === 'function') transports.http = true;
    manifest.workflows.push({ name, transports });
    localWorkflowHandlers[name] = mod.run;
    if (transports.http) workflowHandlers[name] = mod.run;
    if (typeof mod.route === 'function') workflowRouteMiddleware[name] = mod.route;
  }

  for (const [name, mod] of Object.entries(channelModules)) {
    const channel = mod.channel;
    if (!channel || typeof channel !== 'object' || Array.isArray(channel)) throw new Error('[flue] Channel "' + name + '" must export a created channel as the named "channel" binding.');
    if (!Array.isArray(channel.routes) || channel.routes.length === 0) throw new Error('[flue] Channel "' + name + '" must declare at least one route.');
    const routes = {};
    for (const route of channel.routes) {
      if (!route || typeof route !== 'object' || Array.isArray(route)) throw new Error('[flue] Channel "' + name + '" contains an invalid route declaration.');
      if (typeof route.method !== 'string' || !/^[A-Z]+$/.test(route.method)) throw new Error('[flue] Channel "' + name + '" route method must contain only uppercase ASCII letters.');
      if (typeof route.path !== 'string' || route.path.length < 2 || !route.path.startsWith('/') || route.path.startsWith('//') || route.path.includes('?') || route.path.includes('#')) throw new Error('[flue] Channel "' + name + '" route path must be a non-empty absolute suffix without a query or fragment.');
      const segments = route.path.split('/');
      if (segments.some((segment) => segment === '.' || segment === '..')) throw new Error('[flue] Channel "' + name + '" route path must remain beneath its channel namespace.');
      if (typeof route.handler !== 'function') throw new Error('[flue] Channel "' + name + '" route handler must be callable.');
      const key = route.method + ' ' + route.path;
      if (routes[key] !== undefined) throw new Error('[flue] Channel "' + name + '" declares duplicate route "' + key + '".');
      routes[key] = route.handler;
    }
    channelHandlers[name] = routes;
  }

  return { manifest, createdAgents, dispatchAgentNames, workflowHandlers, localWorkflowHandlers, agentRouteMiddleware, workflowRouteMiddleware, channelHandlers };
}


const agentModules = {
  "maple-chat": handler_maple_chat_0,
};
const workflowModules = {
  "triage": workflow_triage_0,
};
const channelModules = {

};
const normalized = normalizeBuiltModules(agentModules, workflowModules, channelModules);
const { manifest, createdAgents, dispatchAgentNames, workflowHandlers, agentRouteMiddleware, workflowRouteMiddleware, channelHandlers } = normalized;
const agentIdentities = {
  "maple-chat": { bindingName: "FLUE_MAPLE_CHAT_AGENT", className: "FlueMapleChatAgent" },
};
const workflowIdentities = {
  "triage": { bindingName: "FLUE_TRIAGE_WORKFLOW", className: "FlueTriageWorkflow" },
};

const userCloudflare = {};
const reservedCloudflareExportNames = new Set(["FlueMapleChatAgent","FlueTriageWorkflow","FlueRegistry"]);
for (const name of Object.keys(userCloudflare)) {
  if (name === 'default') continue;
  if (reservedCloudflareExportNames.has(name)) {
    throw new Error('[flue] cloudflare.ts export "' + name + '" conflicts with a Flue-generated Worker export. Rename the authored export.');
  }
}
const cloudflareHandlers = 'default' in userCloudflare ? userCloudflare.default : {};
if (typeof cloudflareHandlers !== 'object' || cloudflareHandlers === null || Array.isArray(cloudflareHandlers)) {
  throw new Error('[flue] cloudflare.ts default export must be an object containing non-HTTP Worker handlers.');
}
if ('fetch' in cloudflareHandlers) {
  throw new Error('[flue] cloudflare.ts default export must not define fetch. Use app.ts for custom HTTP handling.');
}

// ─── Sandbox Environments ───────────────────────────────────────────────────

/**
 * Create an empty in-memory sandbox (default).
 */
async function createDefaultEnv() {
  const fs = new InMemoryFs();
  return bashFactoryToSessionEnv(() => new Bash({
    fs,
    network: { dangerouslyAllowFullInternetAccess: true },
  }));
}

const INTERNAL_DISPATCH_PATH = CLOUDFLARE_AGENT_INTERNAL_DISPATCH_PATH;
const dispatchQueue = {
  async enqueue(input) {
    const identity = agentIdentities[input.agent];
    const binding = env?.[identity?.bindingName];
    if (!binding) throw new Error('[flue] dispatch() target agent "' + input.agent + '" Durable Object binding is unavailable.');
    const response = await fetchAgent(binding, input.id, new Request('https://flue.invalid' + INTERNAL_DISPATCH_PATH, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify(input),
    }));
    if (!response.ok) throw new Error('[flue] dispatch() target agent "' + input.agent + '" rejected durable admission with status ' + response.status + '.');
    return response.json();
  },
};

function createContextForRequest(id, runId, payload, doInstance, req, defaultStore, initialEventIndex, dispatchId) {
  return createFlueContext({
    id,
    runId,
    dispatchId,
    payload,
    env: doInstance?.env ?? {},
    req,
    initialEventIndex,
    agentConfig: { packagedSkills, resolveModel },
    createDefaultEnv,
    defaultStore,
  });
}

function createAgentContextForRequest(executionStore, id, payload, doInstance, req, initialEventIndex, dispatchId) {
  return createFlueContext({
    id,
    payload,
    env: doInstance?.env ?? {},
    req,
    initialEventIndex,
    dispatchId,
    agentConfig: { packagedSkills, resolveModel },
    createDefaultEnv,
    defaultStore: executionStore.sessions,
    submissionStore: executionStore.submissions,
  });
}

function createWorkflowContextForRequest(id, runId, payload, doInstance, req, initialEventIndex, dispatchId) {
  const defaultStore = createSqlSessionStore(doInstance.ctx.storage);
  return createContextForRequest(id, runId, payload, doInstance, req, defaultStore, initialEventIndex, dispatchId);
}

function createRunStoreForRequest(doInstance) {
  // Composite run store: per-workflow-DO records plus the FlueRegistry
  // index DO for cross-deployment lookup/listing.
  const sql = doInstance?.ctx?.storage?.sql;
  if (!sql) {
    throw new Error('[flue] Durable Object SQLite storage is unavailable — cannot create the run store. Flue Durable Object classes require SQLite-backed storage.');
  }
  return createCloudflareRunStore(createSqlRunStore(sql), doInstance?.env?.FLUE_REGISTRY);
}

// Falls back to the worker-level env so ambient callers (the listRuns()/
// getRun() primitives, which have no request scope) reach the index too.
function createRunIndexForRequest(reqEnv) {
  return createCloudflareRunIndex((reqEnv ?? env)?.FLUE_REGISTRY);
}

async function fetchAgent(binding, instanceId, request) {
  return (await getAgentByName(binding, instanceId)).fetch(request);
}

function runWithInstanceContext(doInstance, identity, fn) {
  return runWithCloudflareContext(
    {
      env: doInstance.env,
      storage: doInstance.ctx.storage,
      durableObjectIdentity: createDurableObjectIdentity(doInstance, identity),
    },
    fn,
  );
}

function createDurableObjectIdentity(doInstance, identity) {
  return {
    bindingName: identity.bindingName,
    className: identity.className,
    name: doInstance.name,
    id: doInstance.ctx.id.toString(),
  };
}

const eventStreamStores = new WeakMap();

function createEventStreamStoreForInstance(doInstance) {
  const existing = eventStreamStores.get(doInstance);
  if (existing) return existing;
  const sql = doInstance?.ctx?.storage?.sql;
  if (!sql) {
    throw new Error('[flue] Durable Object SQLite storage is unavailable — cannot create the event stream store. Flue Durable Object classes require SQLite-backed storage.');
  }
  const store = new SqliteEventStreamStore(sql);
  eventStreamStores.set(doInstance, store);
  return store;
}

const cloudflareAgents = createCloudflareAgentRuntime({
  createdAgents,
  createContext: ({ executionStore, instance, payload, request, initialEventIndex, dispatchId }) =>
    createAgentContextForRequest(executionStore, instance.name, payload, instance, request, initialEventIndex, dispatchId),
  runWithInstanceContext: (instance, agentName, fn) => runWithInstanceContext(instance, agentRuntimeIdentity(agentName), fn),
  createEventStreamStore: (instance) => createEventStreamStoreForInstance(instance),
});

function assertAgentsDurabilityApi(doInstance, method) {
  if (typeof doInstance[method] !== 'function') {
		throw new Error(
			'[flue] The installed "agents" package does not provide the required Cloudflare Agents SDK method "' +
				method +
				'". Install or upgrade the "agents" package in your project.',
		);
	}
}

async function handleFlueWorkflowFiberRecovered(ctx, doInstance, workflowName) {
  if (!ctx.name || ctx.name !== 'flue:workflow:' + doInstance.name) return;
  const interruptedRunId = doInstance.name;
  const runStore = createRunStoreForRequest(doInstance);
  await failRecoveredRun({
    workflowName,
    id: interruptedRunId,
    runId: interruptedRunId,
    request: new Request('https://flue.invalid/workflows/' + encodeURIComponent(workflowName), { method: 'POST' }),
    error: new Error('Flue workflow execution was interrupted. Start a new workflow run explicitly if retry is appropriate.'),
    runStore,
    eventStreamStore: createEventStreamStoreForInstance(doInstance),
    createContext: (id_, recoveredRunId, payload, req, initialEventIndex) => createWorkflowContextForRequest(id_, recoveredRunId, payload, doInstance, req, initialEventIndex),
  });
}

async function dispatchWorkflow(request, doInstance, workflowName) {
  // The DO room name is the workflow instance id. For workflows that
  // equals the run id (one run per instance), so callers reach this DO
  // either by starting a new run (POST /workflows/:name → routed by the
  // outer worker) or by hitting a /runs/:runId subroute on an existing
  // instance.
  const instanceId = doInstance.name;
  const runRoute = parseRunRoute(request);
  if (runRoute) {
    // DS stream read (GET/HEAD on /runs/:runId) — use EventStreamStore.
    if (runRoute.action === 'ds-stream') {
      const store = createEventStreamStoreForInstance(doInstance);
      const streamPath = 'runs/' + runRoute.runId;
      if (request.method === 'HEAD') return await handleStreamHead(store, streamPath);
      return handleStreamRead({ store, path: streamPath, request });
    }
    return handleRunRouteRequest({
      workflowName,
      runId: instanceId,
      runStore: createRunStoreForRequest(doInstance),
    });
  }

  if (!parseWorkflowStart(request, workflowName)) return null;
  const handler = workflowHandlers[workflowName];
  if (!handler) return null;
  const identity = workflowRuntimeIdentity(workflowName);
  return runWithInstanceContext(doInstance, identity, () => handleWorkflowRequest({
      request,
      workflowName,
      runId: instanceId,
      handler,
      runStore: createRunStoreForRequest(doInstance),
      eventStreamStore: createEventStreamStoreForInstance(doInstance),
      createContext: (id_, runId, payload, req, initialEventIndex, dispatchId) => createWorkflowContextForRequest(id_, runId, payload, doInstance, req, initialEventIndex, dispatchId),
      startWorkflowAdmission: (runId, run) => {
        assertAgentsDurabilityApi(doInstance, 'runFiber');
        return doInstance.runFiber('flue:workflow:' + runId, () => runWithInstanceContext(doInstance, identity, run));
      },
    }));
}



function workflowRuntimeIdentity(workflowName) {
  return workflowIdentities[workflowName];
}

function agentRuntimeIdentity(agentName) {
  return agentIdentities[agentName];
}

function parseWorkflowStart(request, workflowName) {
  if (request.method !== 'POST') return false;
  const url = new URL(request.url);
  const segments = url.pathname.split('/').filter(Boolean);
  if (segments.length !== 2 || segments[0] !== 'workflows') return false;
  return decodeURIComponent(segments[1] || '') === workflowName;
}

function parseRunRoute(request) {
  const url = new URL(request.url);
  const segments = url.pathname.split('/').filter(Boolean);
  if (segments.length !== 2 || segments[0] !== 'runs') return null;
  let runId;
  try {
    runId = decodeURIComponent(segments[1] || '');
  } catch {
    return null;
  }
  if (!runId) return null;
  // GET /runs/:runId?meta → run-record view; GET/HEAD otherwise → DS
  // stream read. The outer worker rejects other methods before
  // forwarding, so nothing else routes here.
  if (request.method === 'GET' && url.searchParams.has('meta')) return { action: 'get', runId };
  if (request.method === 'GET' || request.method === 'HEAD') return { action: 'ds-stream', runId };
  return null;
}

// ─── Per-Agent / Per-Workflow Durable Object Classes ──────────────────────

const agentExtension0 = resolveCloudflareExtension(agentModules["maple-chat"], "maple-chat", 'Agent');
const FlueMapleChatAgent = class FlueMapleChatAgent extends agentExtension0.base(Agent) {
  constructor(ctx, env) {
    const prepared = cloudflareAgents.prepare({ storage: ctx.storage, className: "FlueMapleChatAgent", agentName: "maple-chat" });
    super(ctx, env);
    cloudflareAgents.attach(this, prepared);
  }

  onStart(props) {
    return cloudflareAgents.onStart(this, () => typeof super.onStart === 'function' ? super.onStart(props) : undefined);
  }

  __flueWakeAgentSubmissions() {
    return cloudflareAgents.wakeSubmissions(this);
  }

  onRequest(request) {
    return cloudflareAgents.onRequest(this, request);
  }

  onFiberRecovered(ctx) {
    return cloudflareAgents.onFiberRecovered(this, ctx, () => typeof super.onFiberRecovered === 'function' ? super.onFiberRecovered(ctx) : undefined);
  }
};
const WrappedFlueMapleChatAgent = agentExtension0.wrap(FlueMapleChatAgent);
export { WrappedFlueMapleChatAgent as FlueMapleChatAgent };
const workflowExtension0 = resolveCloudflareExtension(workflowModules["triage"], "triage", 'Workflow');
const FlueTriageWorkflow = class FlueTriageWorkflow extends workflowExtension0.base(Agent) {
  async onRequest(request) {
    return dispatchWorkflow(request, this, "triage");
  }

  async onFiberRecovered(ctx) {
    if (ctx.name?.startsWith('flue:workflow:')) {
      return handleFlueWorkflowFiberRecovered(ctx, this, "triage");
    }
    if (typeof super.onFiberRecovered === 'function') {
      return super.onFiberRecovered(ctx);
    }
  }
};
const WrappedFlueTriageWorkflow = workflowExtension0.wrap(FlueTriageWorkflow);
export { WrappedFlueTriageWorkflow as FlueTriageWorkflow };

export { FlueRegistry };

// ─── Runtime seed ───────────────────────────────────────────────────────────

configureFlueRuntime({
  target: 'cloudflare',
  devMode: import.meta.env.DEV,
  runtimeVersion: "1.0.0-beta.2",
  manifest,
  dispatchQueue,
  resolveDispatchAgentName: (agent) => dispatchAgentNames.get(agent),
  agentRouteMiddleware,
  workflowRouteMiddleware,
  channelHandlers,
  routeAgentRequest: async (request, reqEnv, target) => {
    const binding = reqEnv?.[agentIdentities[target.agentName]?.bindingName];
    if (!binding) return null;
    return fetchAgent(binding, target.instanceId, request);
  },
  routeWorkflowRequest: async (request, reqEnv, target) => {
    const binding = reqEnv?.[workflowIdentities[target.workflowName]?.bindingName];
    if (!binding) return null;
    return fetchAgent(binding, target.instanceId, request);
  },
  createRunIndexForRequest,
  routeRunRequest: async (request, reqEnv, target) => {
    // reqEnv is undefined for ambient callers (the getRun() primitive);
    // fall back to the worker-level env.
    const binding = (reqEnv ?? env)?.[workflowIdentities[target.workflowName]?.bindingName];
    if (!binding) return null;
    return fetchAgent(binding, target.runId, request);
  },
});

// ─── App composition ────────────────────────────────────────────────────────

// User-supplied app.ts. Their default export owns the entire request
// pipeline — the worker just verifies a fetch method exists and pipes
// through. The default flue() handler is available for them to mount
// however they want; this file does not impose a composition.
const flueApp = userApp;
if (!flueApp || typeof flueApp.fetch !== 'function') {
  throw new Error(
    '[flue] app.ts default export must be a Hono app or an object with a fetch(request, env, ctx) method.'
  );
}

export default {
  ...cloudflareHandlers,
  fetch(request, env, ctx) {
    return flueApp.fetch(request, env, ctx);
  },
};
