{{- if and .Values.maple.clickhouse.password.value (not .Values.maple.clickhouse.password.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "maple-otel.clickhouseSecretName" . }}
  labels:
    {{- include "maple-otel.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "maple-otel.clickhouseSecretKey" . }}: {{ .Values.maple.clickhouse.password.value | quote }}
{{- end }}
