-- This file is generated by scripts/generate-clickhouse-schema-sql.ts
-- Do not edit manually. Run `bun run clickhouse:schema` to regenerate.
-- projectRevision: d58ce4a83d3ad3f3a29b9bb972272b757547ae793c050194354454634f3abccd

CREATE TABLE IF NOT EXISTS alert_checks (
    OrgId LowCardinality(String),
    RuleId String,
    GroupKey String,
    Timestamp DateTime64(3),
    Status LowCardinality(String),
    SignalType LowCardinality(String),
    Comparator LowCardinality(String),
    Threshold Float64,
    ObservedValue Nullable(Float64),
    SampleCount UInt32,
    WindowMinutes UInt16,
    WindowStart DateTime64(3),
    WindowEnd DateTime64(3),
    ConsecutiveBreaches UInt16,
    ConsecutiveHealthy UInt16,
    IncidentId Nullable(String),
    IncidentTransition LowCardinality(String),
    EvaluationDurationMs UInt32
)
ENGINE = MergeTree
PARTITION BY toDate(Timestamp)
ORDER BY (OrgId, RuleId, GroupKey, Timestamp)
TTL toDate(Timestamp) + INTERVAL 90 DAY;

CREATE TABLE IF NOT EXISTS attribute_keys_hourly (
    OrgId LowCardinality(String),
    Hour DateTime,
    AttributeKey LowCardinality(String),
    AttributeScope LowCardinality(String),
    UsageCount SimpleAggregateFunction(sum, UInt64)
)
ENGINE = AggregatingMergeTree
PARTITION BY toDate(Hour)
ORDER BY (OrgId, AttributeScope, Hour, AttributeKey)
TTL Hour + INTERVAL 90 DAY;

CREATE TABLE IF NOT EXISTS attribute_values_hourly (
    OrgId LowCardinality(String),
    Hour DateTime,
    AttributeKey LowCardinality(String),
    AttributeValue String,
    AttributeScope LowCardinality(String),
    UsageCount SimpleAggregateFunction(sum, UInt64)
)
ENGINE = AggregatingMergeTree
PARTITION BY toDate(Hour)
ORDER BY (OrgId, AttributeScope, AttributeKey, Hour, AttributeValue)
TTL Hour + INTERVAL 90 DAY;

CREATE TABLE IF NOT EXISTS error_events (
    OrgId LowCardinality(String),
    Timestamp DateTime,
    TraceId String,
    SpanId String,
    ParentSpanId String DEFAULT '__unset__',
    ServiceName LowCardinality(String),
    DeploymentEnv LowCardinality(String),
    ExceptionType LowCardinality(String),
    ExceptionMessage String,
    ExceptionStacktrace String,
    TopFrame String,
    FingerprintHash UInt64,
    StatusMessage String,
    Duration UInt64,
    ErrorLabel String
)
ENGINE = MergeTree
PARTITION BY toDate(Timestamp)
ORDER BY (OrgId, FingerprintHash, Timestamp)
TTL Timestamp + INTERVAL 90 DAY;

CREATE TABLE IF NOT EXISTS error_events_by_time (
    OrgId LowCardinality(String),
    Timestamp DateTime,
    TraceId String,
    SpanId String,
    ParentSpanId String DEFAULT '__unset__',
    ServiceName LowCardinality(String),
    DeploymentEnv LowCardinality(String),
    ExceptionType LowCardinality(String),
    ExceptionMessage String,
    ExceptionStacktrace String,
    TopFrame String,
    FingerprintHash UInt64,
    StatusMessage String,
    Duration UInt64,
    ErrorLabel String
)
ENGINE = MergeTree
PARTITION BY toDate(Timestamp)
ORDER BY (OrgId, Timestamp, FingerprintHash)
TTL Timestamp + INTERVAL 90 DAY;

CREATE TABLE IF NOT EXISTS error_spans (
    OrgId LowCardinality(String),
    Timestamp DateTime,
    TraceId String,
    SpanId String,
    ParentSpanId String DEFAULT '__unset__',
    ServiceName LowCardinality(String),
    StatusMessage String,
    Duration UInt64,
    DeploymentEnv LowCardinality(String)
)
ENGINE = MergeTree
PARTITION BY toDate(Timestamp)
ORDER BY (OrgId, ServiceName, Timestamp)
TTL Timestamp + INTERVAL 90 DAY;

CREATE TABLE IF NOT EXISTS logs (
    OrgId LowCardinality(String),
    Timestamp DateTime64(9),
    TimestampTime DateTime,
    TraceId String,
    SpanId String,
    TraceFlags UInt8,
    SeverityText LowCardinality(String),
    SeverityNumber UInt8,
    ServiceName LowCardinality(String),
    Body String,
    ResourceSchemaUrl String,
    ResourceAttributes Map(LowCardinality(String), String),
    ScopeSchemaUrl String,
    ScopeName String,
    ScopeVersion String,
    ScopeAttributes Map(LowCardinality(String), String),
    LogAttributes Map(LowCardinality(String), String),
    INDEX idx_trace_id TraceId TYPE bloom_filter(0.01) GRANULARITY 1
)
ENGINE = MergeTree
PARTITION BY toDate(TimestampTime)
ORDER BY (OrgId, ServiceName, TimestampTime, Timestamp)
TTL toDate(TimestampTime) + INTERVAL 30 DAY;

CREATE TABLE IF NOT EXISTS logs_aggregates_hourly (
    OrgId LowCardinality(String),
    Hour DateTime,
    ServiceName LowCardinality(String),
    SeverityText LowCardinality(String),
    DeploymentEnv LowCardinality(String),
    Count SimpleAggregateFunction(sum, UInt64),
    SizeBytes SimpleAggregateFunction(sum, UInt64),
    ServiceNamespace LowCardinality(String),
    INDEX idx_service_namespace ServiceNamespace TYPE set(1000) GRANULARITY 4
)
ENGINE = AggregatingMergeTree
PARTITION BY toDate(Hour)
ORDER BY (OrgId, Hour, ServiceName, SeverityText, DeploymentEnv, ServiceNamespace)
TTL toDate(Hour) + INTERVAL 90 DAY;

CREATE TABLE IF NOT EXISTS metric_catalog (
    OrgId LowCardinality(String),
    Hour DateTime,
    MetricType LowCardinality(String),
    ServiceName LowCardinality(String),
    MetricName LowCardinality(String),
    MetricDescription SimpleAggregateFunction(anyLast, String),
    MetricUnit SimpleAggregateFunction(anyLast, String),
    IsMonotonic SimpleAggregateFunction(anyLast, UInt8),
    DataPointCount SimpleAggregateFunction(sum, UInt64),
    FirstSeen SimpleAggregateFunction(min, DateTime),
    LastSeen SimpleAggregateFunction(max, DateTime)
)
ENGINE = AggregatingMergeTree
PARTITION BY toDate(Hour)
ORDER BY (OrgId, MetricType, ServiceName, MetricName, Hour)
TTL Hour + INTERVAL 90 DAY;

CREATE TABLE IF NOT EXISTS metrics_exponential_histogram (
    OrgId LowCardinality(String),
    ResourceAttributes Map(LowCardinality(String), String),
    ResourceSchemaUrl String,
    ScopeName String,
    ScopeVersion String,
    ScopeAttributes Map(LowCardinality(String), String),
    ScopeSchemaUrl String,
    ServiceName LowCardinality(String),
    MetricName LowCardinality(String),
    MetricDescription LowCardinality(String),
    MetricUnit LowCardinality(String),
    Attributes Map(LowCardinality(String), String),
    StartTimeUnix DateTime64(9),
    TimeUnix DateTime64(9),
    Count UInt64,
    Sum Float64,
    Scale Int32,
    ZeroCount UInt64,
    PositiveOffset Int32,
    PositiveBucketCounts Array(UInt64),
    NegativeOffset Int32,
    NegativeBucketCounts Array(UInt64),
    ExemplarsTraceId Array(String),
    ExemplarsSpanId Array(String),
    ExemplarsTimestamp Array(DateTime64(9)),
    ExemplarsValue Array(Float64),
    ExemplarsFilteredAttributes Array(Map(LowCardinality(String), String)),
    Flags UInt32,
    Min Nullable(Float64),
    Max Nullable(Float64),
    AggregationTemporality Int32
)
ENGINE = MergeTree
PARTITION BY toDate(TimeUnix)
ORDER BY (OrgId, ServiceName, MetricName, Attributes, toUnixTimestamp64Nano(TimeUnix))
TTL toDate(TimeUnix) + INTERVAL 90 DAY;

CREATE TABLE IF NOT EXISTS metrics_gauge (
    OrgId LowCardinality(String),
    ResourceAttributes Map(LowCardinality(String), String),
    ResourceSchemaUrl String,
    ScopeName String,
    ScopeVersion String,
    ScopeAttributes Map(LowCardinality(String), String),
    ScopeSchemaUrl String,
    ServiceName LowCardinality(String),
    MetricName LowCardinality(String),
    MetricDescription LowCardinality(String),
    MetricUnit LowCardinality(String),
    Attributes Map(LowCardinality(String), String),
    StartTimeUnix DateTime64(9),
    TimeUnix DateTime64(9),
    Value Float64,
    Flags UInt32,
    ExemplarsTraceId Array(String),
    ExemplarsSpanId Array(String),
    ExemplarsTimestamp Array(DateTime64(9)),
    ExemplarsValue Array(Float64),
    ExemplarsFilteredAttributes Array(Map(LowCardinality(String), String))
)
ENGINE = MergeTree
PARTITION BY toDate(TimeUnix)
ORDER BY (OrgId, ServiceName, MetricName, Attributes, toUnixTimestamp64Nano(TimeUnix))
TTL toDate(TimeUnix) + INTERVAL 90 DAY;

CREATE TABLE IF NOT EXISTS metrics_histogram (
    OrgId LowCardinality(String),
    ResourceAttributes Map(LowCardinality(String), String),
    ResourceSchemaUrl String,
    ScopeName String,
    ScopeVersion String,
    ScopeAttributes Map(LowCardinality(String), String),
    ScopeSchemaUrl String,
    ServiceName LowCardinality(String),
    MetricName LowCardinality(String),
    MetricDescription LowCardinality(String),
    MetricUnit LowCardinality(String),
    Attributes Map(LowCardinality(String), String),
    StartTimeUnix DateTime64(9),
    TimeUnix DateTime64(9),
    Count UInt64,
    Sum Float64,
    BucketCounts Array(UInt64),
    ExplicitBounds Array(Float64),
    ExemplarsTraceId Array(String),
    ExemplarsSpanId Array(String),
    ExemplarsTimestamp Array(DateTime64(9)),
    ExemplarsValue Array(Float64),
    ExemplarsFilteredAttributes Array(Map(LowCardinality(String), String)),
    Flags UInt32,
    Min Nullable(Float64),
    Max Nullable(Float64),
    AggregationTemporality Int32
)
ENGINE = MergeTree
PARTITION BY toDate(TimeUnix)
ORDER BY (OrgId, ServiceName, MetricName, Attributes, toUnixTimestamp64Nano(TimeUnix))
TTL toDate(TimeUnix) + INTERVAL 90 DAY;

CREATE TABLE IF NOT EXISTS metrics_sum (
    OrgId LowCardinality(String),
    ResourceAttributes Map(LowCardinality(String), String),
    ResourceSchemaUrl String,
    ScopeName String,
    ScopeVersion String,
    ScopeAttributes Map(LowCardinality(String), String),
    ScopeSchemaUrl String,
    ServiceName LowCardinality(String),
    MetricName LowCardinality(String),
    MetricDescription LowCardinality(String),
    MetricUnit LowCardinality(String),
    Attributes Map(LowCardinality(String), String),
    StartTimeUnix DateTime64(9),
    TimeUnix DateTime64(9),
    Value Float64,
    Flags UInt32,
    ExemplarsTraceId Array(String),
    ExemplarsSpanId Array(String),
    ExemplarsTimestamp Array(DateTime64(9)),
    ExemplarsValue Array(Float64),
    ExemplarsFilteredAttributes Array(Map(LowCardinality(String), String)),
    AggregationTemporality Int32,
    IsMonotonic Bool
)
ENGINE = MergeTree
PARTITION BY toDate(TimeUnix)
ORDER BY (OrgId, ServiceName, MetricName, Attributes, toUnixTimestamp64Nano(TimeUnix))
TTL toDate(TimeUnix) + INTERVAL 90 DAY;

CREATE TABLE IF NOT EXISTS service_address_resolutions_hourly (
    OrgId LowCardinality(String),
    Hour DateTime,
    SourceService LowCardinality(String),
    ParentServerAddress String,
    ResolvedTargetService LowCardinality(String),
    DeploymentEnv LowCardinality(String)
)
ENGINE = ReplacingMergeTree
PARTITION BY toDate(Hour)
ORDER BY (OrgId, Hour, DeploymentEnv, SourceService, ParentServerAddress, ResolvedTargetService)
TTL toDate(Hour) + INTERVAL 90 DAY;

CREATE TABLE IF NOT EXISTS service_external_edges_hourly (
    OrgId LowCardinality(String),
    Hour DateTime,
    ServiceName LowCardinality(String),
    TargetType LowCardinality(String),
    TargetSystem LowCardinality(String),
    TargetName String,
    DeploymentEnv LowCardinality(String),
    CallCount SimpleAggregateFunction(sum, UInt64),
    ErrorCount SimpleAggregateFunction(sum, UInt64),
    DurationSumMs SimpleAggregateFunction(sum, Float64),
    MaxDurationMs SimpleAggregateFunction(max, Float64),
    SampleRateSum SimpleAggregateFunction(sum, Float64)
)
ENGINE = AggregatingMergeTree
PARTITION BY toDate(Hour)
ORDER BY (OrgId, Hour, DeploymentEnv, ServiceName, TargetType, TargetSystem, TargetName)
TTL toDate(Hour) + INTERVAL 90 DAY;

CREATE TABLE IF NOT EXISTS service_map_children (
    OrgId LowCardinality(String),
    Timestamp DateTime,
    TraceId String,
    ParentSpanId String,
    ServiceName LowCardinality(String),
    SpanKind LowCardinality(String),
    Duration UInt64,
    StatusCode LowCardinality(String),
    TraceState String,
    DeploymentEnv LowCardinality(String)
)
ENGINE = MergeTree
PARTITION BY toDate(Timestamp)
ORDER BY (OrgId, TraceId, ParentSpanId, Timestamp)
TTL Timestamp + INTERVAL 30 DAY;

CREATE TABLE IF NOT EXISTS service_map_db_edges_hourly (
    OrgId LowCardinality(String),
    Hour DateTime,
    ServiceName LowCardinality(String),
    DbSystem LowCardinality(String),
    DeploymentEnv LowCardinality(String),
    CallCount SimpleAggregateFunction(sum, UInt64),
    ErrorCount SimpleAggregateFunction(sum, UInt64),
    DurationSumMs SimpleAggregateFunction(sum, Float64),
    MaxDurationMs SimpleAggregateFunction(max, Float64),
    SampledSpanCount SimpleAggregateFunction(sum, UInt64),
    UnsampledSpanCount SimpleAggregateFunction(sum, UInt64),
    SampleRateSum SimpleAggregateFunction(sum, Float64)
)
ENGINE = AggregatingMergeTree
PARTITION BY toDate(Hour)
ORDER BY (OrgId, Hour, DeploymentEnv, ServiceName, DbSystem)
TTL toDate(Hour) + INTERVAL 90 DAY;

CREATE TABLE IF NOT EXISTS service_map_db_query_shapes_hourly (
    OrgId LowCardinality(String),
    Hour DateTime,
    ServiceName LowCardinality(String),
    DbSystem LowCardinality(String),
    DeploymentEnv LowCardinality(String),
    QueryKey String,
    QueryLabel SimpleAggregateFunction(any, String),
    SampleStatement SimpleAggregateFunction(any, String),
    CallCount SimpleAggregateFunction(sum, UInt64),
    ErrorCount SimpleAggregateFunction(sum, UInt64),
    EstimatedCount SimpleAggregateFunction(sum, Float64),
    EstimatedErrorCount SimpleAggregateFunction(sum, Float64),
    WeightedDurationSumMs SimpleAggregateFunction(sum, Float64),
    DurationQuantiles AggregateFunction(quantilesTDigestWeighted(0.5, 0.95), UInt64, UInt32)
)
ENGINE = AggregatingMergeTree
PARTITION BY toDate(Hour)
ORDER BY (OrgId, Hour, DeploymentEnv, ServiceName, DbSystem, QueryKey)
TTL toDate(Hour) + INTERVAL 90 DAY;

CREATE TABLE IF NOT EXISTS service_map_edges_hourly (
    OrgId LowCardinality(String),
    Hour DateTime,
    SourceService LowCardinality(String),
    TargetService String,
    DeploymentEnv LowCardinality(String),
    CallCount SimpleAggregateFunction(sum, UInt64),
    ErrorCount SimpleAggregateFunction(sum, UInt64),
    DurationSumMs SimpleAggregateFunction(sum, Float64),
    MaxDurationMs SimpleAggregateFunction(max, Float64),
    SampledSpanCount SimpleAggregateFunction(sum, UInt64),
    UnsampledSpanCount SimpleAggregateFunction(sum, UInt64),
    SampleRateSum SimpleAggregateFunction(sum, Float64)
)
ENGINE = AggregatingMergeTree
PARTITION BY toDate(Hour)
ORDER BY (OrgId, Hour, DeploymentEnv, SourceService, TargetService)
TTL toDate(Hour) + INTERVAL 90 DAY;

CREATE TABLE IF NOT EXISTS service_map_spans (
    OrgId LowCardinality(String),
    Timestamp DateTime,
    TraceId String,
    SpanId String,
    ParentSpanId String,
    ServiceName LowCardinality(String),
    SpanKind LowCardinality(String),
    Duration UInt64,
    StatusCode LowCardinality(String),
    TraceState String,
    DeploymentEnv LowCardinality(String)
)
ENGINE = MergeTree
PARTITION BY toDate(Timestamp)
ORDER BY (OrgId, TraceId, SpanId, Timestamp)
TTL Timestamp + INTERVAL 30 DAY;

CREATE TABLE IF NOT EXISTS service_overview_spans (
    OrgId LowCardinality(String),
    Timestamp DateTime,
    ServiceName LowCardinality(String),
    Duration UInt64,
    StatusCode LowCardinality(String),
    TraceState String,
    DeploymentEnv LowCardinality(String),
    CommitSha LowCardinality(String),
    SampleRate Float64 DEFAULT 1,
    ServiceNamespace LowCardinality(String),
    INDEX idx_service_namespace ServiceNamespace TYPE set(1000) GRANULARITY 4
)
ENGINE = MergeTree
PARTITION BY toDate(Timestamp)
ORDER BY (OrgId, ServiceName, Timestamp)
TTL Timestamp + INTERVAL 30 DAY;

CREATE TABLE IF NOT EXISTS service_platforms_hourly (
    OrgId LowCardinality(String),
    Hour DateTime,
    ServiceName LowCardinality(String),
    DeploymentEnv LowCardinality(String),
    K8sCluster SimpleAggregateFunction(max, String),
    K8sPodName SimpleAggregateFunction(max, String),
    K8sDeploymentName SimpleAggregateFunction(max, String),
    K8sStatefulSetName SimpleAggregateFunction(max, String),
    K8sDaemonSetName SimpleAggregateFunction(max, String),
    K8sNamespaceName SimpleAggregateFunction(max, String),
    CloudPlatform SimpleAggregateFunction(max, String),
    CloudProvider SimpleAggregateFunction(max, String),
    FaasName SimpleAggregateFunction(max, String),
    MapleSdkType SimpleAggregateFunction(max, String),
    ProcessRuntimeName SimpleAggregateFunction(max, String),
    SpanCount SimpleAggregateFunction(sum, UInt64)
)
ENGINE = AggregatingMergeTree
PARTITION BY toDate(Hour)
ORDER BY (OrgId, Hour, ServiceName, DeploymentEnv)
TTL toDate(Hour) + INTERVAL 90 DAY;

CREATE TABLE IF NOT EXISTS service_usage (
    OrgId LowCardinality(String),
    ServiceName LowCardinality(String),
    Hour DateTime,
    LogCount UInt64,
    LogSizeBytes UInt64,
    TraceCount UInt64,
    TraceSizeBytes UInt64,
    SumMetricCount UInt64,
    SumMetricSizeBytes UInt64,
    GaugeMetricCount UInt64,
    GaugeMetricSizeBytes UInt64,
    HistogramMetricCount UInt64,
    HistogramMetricSizeBytes UInt64,
    ExpHistogramMetricCount UInt64,
    ExpHistogramMetricSizeBytes UInt64
)
ENGINE = SummingMergeTree
ORDER BY (OrgId, ServiceName, Hour)
TTL Hour + INTERVAL 365 DAY;

CREATE TABLE IF NOT EXISTS session_events (
    OrgId LowCardinality(String),
    SessionId String,
    Timestamp DateTime64(9),
    Seq UInt32 DEFAULT 0,
    Type LowCardinality(String),
    Url String DEFAULT '',
    TraceId String DEFAULT '',
    Level LowCardinality(String) DEFAULT '',
    Message String DEFAULT '',
    TargetSelector String DEFAULT '',
    TargetText String DEFAULT '',
    NetMethod LowCardinality(String) DEFAULT '',
    NetUrl String DEFAULT '',
    NetStatus UInt16 DEFAULT 0,
    NetDurationMs UInt32 DEFAULT 0,
    ErrorStack String DEFAULT '',
    Attributes Map(LowCardinality(String), String)
)
ENGINE = MergeTree
PARTITION BY toDate(Timestamp)
ORDER BY (OrgId, SessionId, Timestamp, Seq)
TTL toDate(Timestamp) + INTERVAL 30 DAY;

CREATE TABLE IF NOT EXISTS session_replay_events (
    OrgId LowCardinality(String),
    SessionId String,
    ChunkSeq UInt32,
    Timestamp DateTime64(9),
    DurationMs UInt32 DEFAULT 0,
    EventCount UInt32 DEFAULT 0,
    ByteSize UInt32 DEFAULT 0,
    Events String,
    IsCheckpoint UInt8 DEFAULT 0
)
ENGINE = MergeTree
PARTITION BY toDate(Timestamp)
ORDER BY (OrgId, SessionId, ChunkSeq)
TTL toDate(Timestamp) + INTERVAL 30 DAY;

CREATE TABLE IF NOT EXISTS session_replays (
    OrgId LowCardinality(String),
    SessionId String,
    StartTime DateTime64(9),
    EndTime Nullable(DateTime64(9)),
    DurationMs Nullable(UInt32),
    Status LowCardinality(String),
    UserId String,
    UrlInitial String,
    UserAgent String,
    BrowserName LowCardinality(String),
    OsName LowCardinality(String),
    DeviceType LowCardinality(String),
    Country LowCardinality(String) DEFAULT '',
    ServiceName LowCardinality(String),
    PageViews UInt32 DEFAULT 0,
    ClickCount UInt32 DEFAULT 0,
    ErrorCount UInt32 DEFAULT 0,
    TraceIds Array(String) DEFAULT [],
    ResourceAttributes Map(LowCardinality(String), String),
    Version UInt32
)
ENGINE = ReplacingMergeTree
PARTITION BY toDate(StartTime)
ORDER BY (OrgId, SessionId)
TTL toDate(StartTime) + INTERVAL 30 DAY;

CREATE TABLE IF NOT EXISTS span_metrics_calls_hourly (
    OrgId LowCardinality(String),
    Hour DateTime,
    ServiceName LowCardinality(String),
    MetricName LowCardinality(String),
    SpanKind LowCardinality(String),
    AttrFingerprint UInt64,
    ResourceFingerprint UInt64,
    StartTimeUnix DateTime64(9),
    LastValue AggregateFunction(argMax, Float64, DateTime64(9))
)
ENGINE = AggregatingMergeTree
PARTITION BY toDate(Hour)
ORDER BY (OrgId, Hour, ServiceName, MetricName, SpanKind, AttrFingerprint, ResourceFingerprint, StartTimeUnix)
TTL toDate(Hour) + INTERVAL 90 DAY;

CREATE TABLE IF NOT EXISTS trace_detail_spans (
    OrgId LowCardinality(String),
    Timestamp DateTime64(9),
    TraceId String,
    SpanId String,
    ParentSpanId String,
    SpanName LowCardinality(String),
    SpanKind LowCardinality(String),
    ServiceName LowCardinality(String),
    Duration UInt64 DEFAULT 0,
    StatusCode LowCardinality(String),
    StatusMessage String,
    SpanAttributes Map(LowCardinality(String), String),
    ResourceAttributes Map(LowCardinality(String), String),
    EventsTimestamp Array(DateTime64(9)),
    EventsName Array(LowCardinality(String)),
    EventsAttributes Array(Map(LowCardinality(String), String))
)
ENGINE = MergeTree
PARTITION BY toDate(Timestamp)
ORDER BY (OrgId, TraceId, SpanId)
TTL toDate(Timestamp) + INTERVAL 30 DAY;

CREATE TABLE IF NOT EXISTS trace_list_mv (
    OrgId LowCardinality(String),
    TraceId String,
    Timestamp DateTime,
    ServiceName LowCardinality(String),
    SpanName String,
    SpanKind LowCardinality(String),
    Duration UInt64,
    StatusCode LowCardinality(String),
    HttpMethod LowCardinality(String),
    HttpRoute String,
    HttpStatusCode LowCardinality(String),
    DeploymentEnv LowCardinality(String),
    HasError UInt8,
    TraceState String,
    ServiceNamespace LowCardinality(String),
    INDEX idx_service_namespace ServiceNamespace TYPE set(1000) GRANULARITY 4
)
ENGINE = MergeTree
PARTITION BY toDate(Timestamp)
ORDER BY (OrgId, Timestamp, TraceId)
TTL Timestamp + INTERVAL 30 DAY;

CREATE TABLE IF NOT EXISTS traces (
    OrgId LowCardinality(String),
    Timestamp DateTime64(9),
    TraceId String,
    SpanId String,
    ParentSpanId String,
    TraceState String,
    SpanName LowCardinality(String),
    SpanKind LowCardinality(String),
    ServiceName LowCardinality(String),
    ResourceSchemaUrl String,
    ResourceAttributes Map(LowCardinality(String), String),
    ScopeSchemaUrl String,
    ScopeName String,
    ScopeVersion String,
    ScopeAttributes Map(LowCardinality(String), String),
    Duration UInt64 DEFAULT 0,
    StatusCode LowCardinality(String),
    StatusMessage String,
    SpanAttributes Map(LowCardinality(String), String),
    EventsTimestamp Array(DateTime64(9)),
    EventsName Array(LowCardinality(String)),
    EventsAttributes Array(Map(LowCardinality(String), String)),
    LinksTraceId Array(String),
    LinksSpanId Array(String),
    LinksTraceState Array(String),
    LinksAttributes Array(Map(LowCardinality(String), String)),
    SampleRate Float64 DEFAULT multiIf(SpanAttributes['SampleRate'] != '' AND toFloat64OrZero(SpanAttributes['SampleRate']) >= 1.0, toFloat64OrZero(SpanAttributes['SampleRate']), match(TraceState, 'th:[0-9a-f]+'), 1.0 / greatest(1.0 - reinterpretAsUInt64(reverse(unhex(rightPad(extract(TraceState, 'th:([0-9a-f]+)'), 16, '0')))) / pow(2.0, 64), 0.0001), 1.0),
    IsEntryPoint UInt8 DEFAULT if(SpanKind IN ('Server', 'Consumer') OR ParentSpanId = '', 1, 0),
    INDEX idx_trace_id TraceId TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_span_attr_keys mapKeys(SpanAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_span_attr_vals mapValues(SpanAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_resource_attr_keys mapKeys(ResourceAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_resource_attr_vals mapValues(ResourceAttributes) TYPE bloom_filter(0.01) GRANULARITY 1
)
ENGINE = MergeTree
PARTITION BY toDate(Timestamp)
ORDER BY (OrgId, ServiceName, SpanName, toDateTime(Timestamp))
TTL toDate(Timestamp) + INTERVAL 30 DAY;

CREATE TABLE IF NOT EXISTS traces_aggregates_hourly (
    OrgId LowCardinality(String),
    Hour DateTime,
    ServiceName LowCardinality(String),
    SpanName LowCardinality(String),
    SpanKind LowCardinality(String),
    StatusCode LowCardinality(String),
    IsEntryPoint UInt8,
    DeploymentEnv LowCardinality(String),
    WeightedCount SimpleAggregateFunction(sum, Float64),
    WeightedDurationSum SimpleAggregateFunction(sum, Float64),
    WeightedErrorCount SimpleAggregateFunction(sum, Float64),
    DurationQuantiles AggregateFunction(quantilesTDigestWeighted(0.5, 0.95, 0.99), UInt64, UInt32),
    DurationMin SimpleAggregateFunction(min, UInt64),
    DurationMax SimpleAggregateFunction(max, UInt64)
)
ENGINE = AggregatingMergeTree
PARTITION BY toDate(Hour)
ORDER BY (OrgId, Hour, ServiceName, SpanName, SpanKind, StatusCode, IsEntryPoint, DeploymentEnv)
TTL toDate(Hour) + INTERVAL 90 DAY;

CREATE MATERIALIZED VIEW IF NOT EXISTS error_events_by_time_mv TO error_events_by_time AS
WITH
          arrayFirstIndex(n -> n = 'exception', EventsName) AS _ei,
          if(_ei > 0, EventsAttributes[_ei]['exception.type'], '') AS _exType,
          if(_ei > 0, EventsAttributes[_ei]['exception.message'], StatusMessage) AS _exMsg,
          if(_ei > 0, EventsAttributes[_ei]['exception.stacktrace'], '') AS _exStack,
          arraySlice(
            arrayFilter(
              line -> match(line, ':[0-9]+|line [0-9]+'),
              splitByChar('\n', _exStack)
            ),
            1, 3
          ) AS _rawFrames,
          arrayMap(
            line -> replaceRegexpAll(line, ':[0-9]+|line [0-9]+|0x[0-9a-fA-F]+', ''),
            _rawFrames
          ) AS _topFrames,
          if(length(_topFrames) > 0, _topFrames[1], '') AS _topFrame,
          arrayStringConcat(_topFrames, '\n') AS _fpFrames,
          -- JSON detection (only consulted when _fpFrames = '')
          isValidJSON(StatusMessage) AS _isJson,
          _isJson AND JSONType(StatusMessage) = 'Object' AS _isJsonObj,
          -- General, KEY-NAME-AGNOSTIC canonical signature: iterate ALL top-level
          -- keys, redact volatile tokens (long hex / numbers) in each raw value, then
          -- sort by "key=value" so key order & whitespace don't matter. No assumption
          -- about which keys exist — works for any producer's JSON shape. (Nested
          -- objects are hashed as their raw substring; only top-level is canonicalized.)
          arrayStringConcat(
            arraySort(
              arrayMap(
                kv -> concat(kv.1, '=', replaceRegexpAll(kv.2, '[0-9a-fA-F]{8,}|[0-9]+', '#')),
                JSONExtractKeysAndValuesRaw(StatusMessage)
              )
            ),
            '|'
          ) AS _jsonSig,
          -- Fold into the existing fallback hash slot. Non-JSON path is unchanged.
          multiIf(
            _fpFrames != '', '',
            _isJsonObj,      _jsonSig,
            replaceRegexpAll(substring(StatusMessage, 1, 200), '[0-9a-fA-F]{8,}|[0-9]+', '#')
          ) AS _msgFallback,
          -- Display-only, best-effort human label (decoupled from the fingerprint:
          -- many labels may map to one hash). The broad key list here is a DISPLAY
          -- heuristic only; the fingerprint above makes no key-name assumption.
          multiIf(
            JSONExtractString(StatusMessage, 'title')   != '', JSONExtractString(StatusMessage, 'title'),
            JSONExtractString(StatusMessage, 'message') != '', JSONExtractString(StatusMessage, 'message'),
            JSONExtractString(StatusMessage, 'error')   != '', JSONExtractString(StatusMessage, 'error'),
            JSONExtractString(StatusMessage, '_tag')    != '', JSONExtractString(StatusMessage, '_tag'),
            JSONExtractString(StatusMessage, 'reason')  != '', JSONExtractString(StatusMessage, 'reason'),
            JSONExtractString(StatusMessage, 'name')    != '', JSONExtractString(StatusMessage, 'name'),
            JSONExtractString(StatusMessage, 'type')    != '', extract(JSONExtractString(StatusMessage, 'type'), '([^/]+)$'),
            'JSON error'
          ) AS _jsonLabel,
          multiIf(
            StatusMessage = '', 'Unknown Error',
            position(StatusMessage, '{ readonly') = 1 OR position(StatusMessage, '└─') > 0,
              if(
                extract(StatusMessage, 'readonly (\\w+)') != '',
                concat('Schema parse error: ', extract(StatusMessage, 'readonly (\\w+)')),
                'Schema parse error'
              ),
            _isJsonObj OR position(StatusMessage, '[') = 1, _jsonLabel,
            left(StatusMessage, multiIf(
              position(StatusMessage, ': ')  > 3, toInt64(position(StatusMessage, ': '))  - 1,
              position(StatusMessage, ' (')  > 3, toInt64(position(StatusMessage, ' (')) - 1,
              position(StatusMessage, '\n') > 3, toInt64(position(StatusMessage, '\n')) - 1,
              least(toInt64(length(StatusMessage)), 150)
            ))
          ) AS _statusLabel,
          if(_exType != '', _exType, _statusLabel) AS _errorLabel
        SELECT
          OrgId,
          toDateTime(Timestamp) AS Timestamp,
          TraceId,
          SpanId,
          ParentSpanId,
          ServiceName,
          ResourceAttributes['deployment.environment'] AS DeploymentEnv,
          _exType AS ExceptionType,
          _exMsg AS ExceptionMessage,
          _exStack AS ExceptionStacktrace,
          _topFrame AS TopFrame,
          cityHash64(OrgId, ServiceName, _exType, _fpFrames, _msgFallback) AS FingerprintHash,
          StatusMessage,
          Duration,
          _errorLabel AS ErrorLabel
        FROM traces
        WHERE StatusCode = 'Error';

CREATE MATERIALIZED VIEW IF NOT EXISTS error_events_mv TO error_events AS
WITH
          arrayFirstIndex(n -> n = 'exception', EventsName) AS _ei,
          if(_ei > 0, EventsAttributes[_ei]['exception.type'], '') AS _exType,
          if(_ei > 0, EventsAttributes[_ei]['exception.message'], StatusMessage) AS _exMsg,
          if(_ei > 0, EventsAttributes[_ei]['exception.stacktrace'], '') AS _exStack,
          arraySlice(
            arrayFilter(
              line -> match(line, ':[0-9]+|line [0-9]+'),
              splitByChar('\n', _exStack)
            ),
            1, 3
          ) AS _rawFrames,
          arrayMap(
            line -> replaceRegexpAll(line, ':[0-9]+|line [0-9]+|0x[0-9a-fA-F]+', ''),
            _rawFrames
          ) AS _topFrames,
          if(length(_topFrames) > 0, _topFrames[1], '') AS _topFrame,
          arrayStringConcat(_topFrames, '\n') AS _fpFrames,
          -- JSON detection (only consulted when _fpFrames = '')
          isValidJSON(StatusMessage) AS _isJson,
          _isJson AND JSONType(StatusMessage) = 'Object' AS _isJsonObj,
          -- General, KEY-NAME-AGNOSTIC canonical signature: iterate ALL top-level
          -- keys, redact volatile tokens (long hex / numbers) in each raw value, then
          -- sort by "key=value" so key order & whitespace don't matter. No assumption
          -- about which keys exist — works for any producer's JSON shape. (Nested
          -- objects are hashed as their raw substring; only top-level is canonicalized.)
          arrayStringConcat(
            arraySort(
              arrayMap(
                kv -> concat(kv.1, '=', replaceRegexpAll(kv.2, '[0-9a-fA-F]{8,}|[0-9]+', '#')),
                JSONExtractKeysAndValuesRaw(StatusMessage)
              )
            ),
            '|'
          ) AS _jsonSig,
          -- Fold into the existing fallback hash slot. Non-JSON path is unchanged.
          multiIf(
            _fpFrames != '', '',
            _isJsonObj,      _jsonSig,
            replaceRegexpAll(substring(StatusMessage, 1, 200), '[0-9a-fA-F]{8,}|[0-9]+', '#')
          ) AS _msgFallback,
          -- Display-only, best-effort human label (decoupled from the fingerprint:
          -- many labels may map to one hash). The broad key list here is a DISPLAY
          -- heuristic only; the fingerprint above makes no key-name assumption.
          multiIf(
            JSONExtractString(StatusMessage, 'title')   != '', JSONExtractString(StatusMessage, 'title'),
            JSONExtractString(StatusMessage, 'message') != '', JSONExtractString(StatusMessage, 'message'),
            JSONExtractString(StatusMessage, 'error')   != '', JSONExtractString(StatusMessage, 'error'),
            JSONExtractString(StatusMessage, '_tag')    != '', JSONExtractString(StatusMessage, '_tag'),
            JSONExtractString(StatusMessage, 'reason')  != '', JSONExtractString(StatusMessage, 'reason'),
            JSONExtractString(StatusMessage, 'name')    != '', JSONExtractString(StatusMessage, 'name'),
            JSONExtractString(StatusMessage, 'type')    != '', extract(JSONExtractString(StatusMessage, 'type'), '([^/]+)$'),
            'JSON error'
          ) AS _jsonLabel,
          multiIf(
            StatusMessage = '', 'Unknown Error',
            position(StatusMessage, '{ readonly') = 1 OR position(StatusMessage, '└─') > 0,
              if(
                extract(StatusMessage, 'readonly (\\w+)') != '',
                concat('Schema parse error: ', extract(StatusMessage, 'readonly (\\w+)')),
                'Schema parse error'
              ),
            _isJsonObj OR position(StatusMessage, '[') = 1, _jsonLabel,
            left(StatusMessage, multiIf(
              position(StatusMessage, ': ')  > 3, toInt64(position(StatusMessage, ': '))  - 1,
              position(StatusMessage, ' (')  > 3, toInt64(position(StatusMessage, ' (')) - 1,
              position(StatusMessage, '\n') > 3, toInt64(position(StatusMessage, '\n')) - 1,
              least(toInt64(length(StatusMessage)), 150)
            ))
          ) AS _statusLabel,
          if(_exType != '', _exType, _statusLabel) AS _errorLabel
        SELECT
          OrgId,
          toDateTime(Timestamp) AS Timestamp,
          TraceId,
          SpanId,
          ParentSpanId,
          ServiceName,
          ResourceAttributes['deployment.environment'] AS DeploymentEnv,
          _exType AS ExceptionType,
          _exMsg AS ExceptionMessage,
          _exStack AS ExceptionStacktrace,
          _topFrame AS TopFrame,
          cityHash64(OrgId, ServiceName, _exType, _fpFrames, _msgFallback) AS FingerprintHash,
          StatusMessage,
          Duration,
          _errorLabel AS ErrorLabel
        FROM traces
        WHERE StatusCode = 'Error';

CREATE MATERIALIZED VIEW IF NOT EXISTS error_spans_mv TO error_spans AS
SELECT
          OrgId,
          toDateTime(Timestamp) AS Timestamp,
          TraceId,
          SpanId,
          ParentSpanId,
          ServiceName,
          StatusMessage,
          Duration,
          ResourceAttributes['deployment.environment'] AS DeploymentEnv
        FROM traces
        WHERE StatusCode = 'Error';

CREATE MATERIALIZED VIEW IF NOT EXISTS log_attribute_keys_mv TO attribute_keys_hourly AS
SELECT
          OrgId,
          toStartOfHour(toDateTime(Timestamp)) AS Hour,
          arrayJoin(mapKeys(LogAttributes)) AS AttributeKey,
          'log' AS AttributeScope,
          count() AS UsageCount
        FROM logs
        WHERE LogAttributes != map()
        GROUP BY OrgId, Hour, AttributeKey, AttributeScope;

CREATE MATERIALIZED VIEW IF NOT EXISTS log_attribute_values_mv TO attribute_values_hourly AS
SELECT
          OrgId,
          toStartOfHour(toDateTime(Timestamp)) AS Hour,
          AttributeKey,
          AttributeValue,
          'log' AS AttributeScope,
          count() AS UsageCount
        FROM logs
        ARRAY JOIN
          mapKeys(LogAttributes) AS AttributeKey,
          mapValues(LogAttributes) AS AttributeValue
        WHERE AttributeValue != ''
        GROUP BY OrgId, Hour, AttributeKey, AttributeValue, AttributeScope;

CREATE MATERIALIZED VIEW IF NOT EXISTS logs_aggregates_hourly_mv TO logs_aggregates_hourly AS
SELECT
          OrgId,
          toStartOfHour(TimestampTime) AS Hour,
          ServiceName,
          SeverityText,
          ResourceAttributes['deployment.environment'] AS DeploymentEnv,
          count() AS Count,
          sum(length(Body) + 200) AS SizeBytes,
          ResourceAttributes['service.namespace'] AS ServiceNamespace
        FROM logs
        GROUP BY OrgId, Hour, ServiceName, SeverityText, DeploymentEnv, ServiceNamespace;

CREATE MATERIALIZED VIEW IF NOT EXISTS metric_attribute_keys_mv TO attribute_keys_hourly AS
SELECT
          OrgId,
          toStartOfHour(toDateTime(TimeUnix)) AS Hour,
          arrayJoin(mapKeys(Attributes)) AS AttributeKey,
          'metric' AS AttributeScope,
          count() AS UsageCount
        FROM metrics_sum
        WHERE Attributes != map()
        GROUP BY OrgId, Hour, AttributeKey, AttributeScope;

CREATE MATERIALIZED VIEW IF NOT EXISTS metric_attribute_values_mv TO attribute_values_hourly AS
SELECT
          OrgId,
          toStartOfHour(toDateTime(TimeUnix)) AS Hour,
          AttributeKey,
          AttributeValue,
          'metric' AS AttributeScope,
          count() AS UsageCount
        FROM metrics_sum
        ARRAY JOIN
          mapKeys(Attributes) AS AttributeKey,
          mapValues(Attributes) AS AttributeValue
        WHERE AttributeValue != ''
        GROUP BY OrgId, Hour, AttributeKey, AttributeValue, AttributeScope;

CREATE MATERIALIZED VIEW IF NOT EXISTS metric_catalog_exp_histogram_mv TO metric_catalog AS
SELECT
          OrgId,
          toStartOfHour(toDateTime(TimeUnix)) AS Hour,
          'exponential_histogram' AS MetricType,
          ServiceName,
          MetricName,
          anyLast(MetricDescription) AS MetricDescription,
          anyLast(MetricUnit) AS MetricUnit,
          toUInt8(0) AS IsMonotonic,
          count() AS DataPointCount,
          min(toDateTime(TimeUnix)) AS FirstSeen,
          max(toDateTime(TimeUnix)) AS LastSeen
        FROM metrics_exponential_histogram
        GROUP BY OrgId, Hour, MetricType, ServiceName, MetricName;

CREATE MATERIALIZED VIEW IF NOT EXISTS metric_catalog_gauge_mv TO metric_catalog AS
SELECT
          OrgId,
          toStartOfHour(toDateTime(TimeUnix)) AS Hour,
          'gauge' AS MetricType,
          ServiceName,
          MetricName,
          anyLast(MetricDescription) AS MetricDescription,
          anyLast(MetricUnit) AS MetricUnit,
          toUInt8(0) AS IsMonotonic,
          count() AS DataPointCount,
          min(toDateTime(TimeUnix)) AS FirstSeen,
          max(toDateTime(TimeUnix)) AS LastSeen
        FROM metrics_gauge
        GROUP BY OrgId, Hour, MetricType, ServiceName, MetricName;

CREATE MATERIALIZED VIEW IF NOT EXISTS metric_catalog_histogram_mv TO metric_catalog AS
SELECT
          OrgId,
          toStartOfHour(toDateTime(TimeUnix)) AS Hour,
          'histogram' AS MetricType,
          ServiceName,
          MetricName,
          anyLast(MetricDescription) AS MetricDescription,
          anyLast(MetricUnit) AS MetricUnit,
          toUInt8(0) AS IsMonotonic,
          count() AS DataPointCount,
          min(toDateTime(TimeUnix)) AS FirstSeen,
          max(toDateTime(TimeUnix)) AS LastSeen
        FROM metrics_histogram
        GROUP BY OrgId, Hour, MetricType, ServiceName, MetricName;

CREATE MATERIALIZED VIEW IF NOT EXISTS metric_catalog_sum_mv TO metric_catalog AS
SELECT
          OrgId,
          toStartOfHour(toDateTime(TimeUnix)) AS Hour,
          'sum' AS MetricType,
          ServiceName,
          MetricName,
          anyLast(MetricDescription) AS MetricDescription,
          anyLast(MetricUnit) AS MetricUnit,
          anyLast(toUInt8(IsMonotonic)) AS IsMonotonic,
          count() AS DataPointCount,
          min(toDateTime(TimeUnix)) AS FirstSeen,
          max(toDateTime(TimeUnix)) AS LastSeen
        FROM metrics_sum
        GROUP BY OrgId, Hour, MetricType, ServiceName, MetricName;

CREATE MATERIALIZED VIEW IF NOT EXISTS service_external_edges_hourly_mv TO service_external_edges_hourly AS
SELECT
          OrgId,
          toStartOfHour(toDateTime(Timestamp)) AS Hour,
          ServiceName,
          multiIf(
            SpanAttributes['messaging.destination'] != '' OR SpanAttributes['messaging.system'] != '', 'messaging',
            SpanAttributes['rpc.service'] != '' OR SpanAttributes['rpc.system'] != '', 'rpc',
            'http'
          ) AS TargetType,
          multiIf(
            SpanAttributes['messaging.destination'] != '' OR SpanAttributes['messaging.system'] != '', SpanAttributes['messaging.system'],
            SpanAttributes['rpc.service'] != '' OR SpanAttributes['rpc.system'] != '', SpanAttributes['rpc.system'],
            ''
          ) AS TargetSystem,
          multiIf(
            SpanAttributes['messaging.destination'] != '' OR SpanAttributes['messaging.system'] != '',
              if(SpanAttributes['messaging.destination'] != '', SpanAttributes['messaging.destination'], SpanAttributes['messaging.system']),
            SpanAttributes['rpc.service'] != '' OR SpanAttributes['rpc.system'] != '',
              if(SpanAttributes['rpc.service'] != '', SpanAttributes['rpc.service'], SpanAttributes['rpc.system']),
            if(SpanAttributes['server.address'] != '',
              SpanAttributes['server.address'],
              if(SpanAttributes['http.host'] != '',
                SpanAttributes['http.host'],
                SpanAttributes['url.authority']))
          ) AS TargetName,
          ResourceAttributes['deployment.environment'] AS DeploymentEnv,
          count() AS CallCount,
          countIf(StatusCode = 'Error') AS ErrorCount,
          sum(Duration / 1000000) AS DurationSumMs,
          max(Duration / 1000000) AS MaxDurationMs,
          sum(SampleRate) AS SampleRateSum
        FROM traces
        WHERE SpanKind IN ('Client', 'Producer')
          AND SpanAttributes['db.system.name'] = ''
          AND ServiceName != ''
          AND (
               SpanAttributes['server.address'] != ''
            OR SpanAttributes['http.host'] != ''
            OR SpanAttributes['url.authority'] != ''
            OR SpanAttributes['messaging.destination'] != ''
            OR SpanAttributes['messaging.system'] != ''
            OR SpanAttributes['rpc.service'] != ''
            OR SpanAttributes['rpc.system'] != ''
          )
        GROUP BY OrgId, Hour, ServiceName, TargetType, TargetSystem, TargetName, DeploymentEnv
        HAVING TargetName != '';

CREATE MATERIALIZED VIEW IF NOT EXISTS service_map_children_mv TO service_map_children AS
SELECT
          OrgId,
          toDateTime(Timestamp) AS Timestamp,
          TraceId,
          ParentSpanId,
          ServiceName,
          SpanKind,
          Duration,
          StatusCode,
          TraceState,
          ResourceAttributes['deployment.environment'] AS DeploymentEnv
        FROM traces
        WHERE SpanKind IN ('Server', 'Consumer')
          AND ParentSpanId != '';

CREATE MATERIALIZED VIEW IF NOT EXISTS service_map_db_edges_hourly_mv TO service_map_db_edges_hourly AS
SELECT
          OrgId,
          toStartOfHour(toDateTime(Timestamp)) AS Hour,
          ServiceName,
          SpanAttributes['db.system.name'] AS DbSystem,
          ResourceAttributes['deployment.environment'] AS DeploymentEnv,
          count() AS CallCount,
          countIf(StatusCode = 'Error') AS ErrorCount,
          sum(Duration / 1000000) AS DurationSumMs,
          max(Duration / 1000000) AS MaxDurationMs,
          countIf(TraceState LIKE '%th:%') AS SampledSpanCount,
          countIf(TraceState = '' OR TraceState NOT LIKE '%th:%') AS UnsampledSpanCount,
          sum(SampleRate) AS SampleRateSum
        FROM traces
        WHERE SpanKind IN ('Client', 'Producer')
          AND SpanAttributes['db.system.name'] != ''
          AND ServiceName != ''
        GROUP BY OrgId, Hour, ServiceName, DbSystem, DeploymentEnv;

CREATE MATERIALIZED VIEW IF NOT EXISTS service_map_db_query_shapes_hourly_mv TO service_map_db_query_shapes_hourly AS
SELECT
          OrgId,
          toStartOfHour(toDateTime(Timestamp)) AS Hour,
          ServiceName,
          coalesce(nullIf(SpanAttributes['db.system.name'], ''), SpanAttributes['db.system']) AS DbSystem,
          ResourceAttributes['deployment.environment'] AS DeploymentEnv,
          coalesce(
  nullIf(SpanAttributes['db.query.fingerprint'], ''),
  nullIf(SpanAttributes['db.statement.fingerprint'], ''),
  nullIf(if(coalesce(nullIf(SpanAttributes['db.query.text'], ''), SpanAttributes['db.statement']) != '', toString(cityHash64(replaceRegexpAll(replaceRegexpAll(replaceRegexpAll(replaceRegexpAll(replaceRegexpAll(lower(coalesce(nullIf(SpanAttributes['db.query.text'], ''), SpanAttributes['db.statement'])), '\'[^\']*\'', '?'), '\\bin\\s*\\([^)]*\\)', 'in (?)'), '[0-9]+(\\.[0-9]+)?', '?'), '\\s+', ' '), '^\\s+|\\s+$', ''))), ''), ''),
  toString(cityHash64(coalesce(
  nullIf(SpanAttributes['db.query.summary'], ''),
  nullIf(if(SpanAttributes['db.operation.name'] != '', trimBoth(concat(SpanAttributes['db.operation.name'], if(coalesce(nullIf(SpanAttributes['db.collection.name'], ''), SpanAttributes['db.namespace']) != '', concat(' ', coalesce(nullIf(SpanAttributes['db.collection.name'], ''), SpanAttributes['db.namespace'])), ''))), ''), ''),
  nullIf(if(coalesce(nullIf(SpanAttributes['db.query.text'], ''), SpanAttributes['db.statement']) != '', trimBoth(concat(upper(extract(coalesce(nullIf(SpanAttributes['db.query.text'], ''), SpanAttributes['db.statement']), '^\\s*(\\w+)')), if(extract(coalesce(nullIf(SpanAttributes['db.query.text'], ''), SpanAttributes['db.statement']), '(?i)(?:from|into|update|join|table)\\s+\\W?([\\w.]+)') != '', concat(' ', extract(coalesce(nullIf(SpanAttributes['db.query.text'], ''), SpanAttributes['db.statement']), '(?i)(?:from|into|update|join|table)\\s+\\W?([\\w.]+)')), ''))), ''), ''),
  nullIf(SpanAttributes['query.context'], ''),
  nullIf(SpanAttributes['db.operation.name'], ''),
  nullIf(SpanAttributes['db.operation'], ''),
  SpanName
)))
) AS QueryKey,
          any(substring(coalesce(
  nullIf(SpanAttributes['db.query.summary'], ''),
  nullIf(if(SpanAttributes['db.operation.name'] != '', trimBoth(concat(SpanAttributes['db.operation.name'], if(coalesce(nullIf(SpanAttributes['db.collection.name'], ''), SpanAttributes['db.namespace']) != '', concat(' ', coalesce(nullIf(SpanAttributes['db.collection.name'], ''), SpanAttributes['db.namespace'])), ''))), ''), ''),
  nullIf(if(coalesce(nullIf(SpanAttributes['db.query.text'], ''), SpanAttributes['db.statement']) != '', trimBoth(concat(upper(extract(coalesce(nullIf(SpanAttributes['db.query.text'], ''), SpanAttributes['db.statement']), '^\\s*(\\w+)')), if(extract(coalesce(nullIf(SpanAttributes['db.query.text'], ''), SpanAttributes['db.statement']), '(?i)(?:from|into|update|join|table)\\s+\\W?([\\w.]+)') != '', concat(' ', extract(coalesce(nullIf(SpanAttributes['db.query.text'], ''), SpanAttributes['db.statement']), '(?i)(?:from|into|update|join|table)\\s+\\W?([\\w.]+)')), ''))), ''), ''),
  nullIf(SpanAttributes['query.context'], ''),
  nullIf(SpanAttributes['db.operation.name'], ''),
  nullIf(SpanAttributes['db.operation'], ''),
  SpanName
), 1, 220)) AS QueryLabel,
          any(substring(coalesce(nullIf(SpanAttributes['db.query.text'], ''), SpanAttributes['db.statement']), 1, 1000)) AS SampleStatement,
          count() AS CallCount,
          countIf(StatusCode = 'Error') AS ErrorCount,
          sum(SampleRate) AS EstimatedCount,
          sumIf(SampleRate, StatusCode = 'Error') AS EstimatedErrorCount,
          sum(toFloat64(Duration) * SampleRate / 1000000) AS WeightedDurationSumMs,
          quantilesTDigestWeightedState(0.5, 0.95)(Duration, toUInt32(greatest(SampleRate, 1.0))) AS DurationQuantiles
        FROM traces
        WHERE SpanKind IN ('Client', 'Producer')
          AND coalesce(nullIf(SpanAttributes['db.system.name'], ''), SpanAttributes['db.system']) != ''
          AND ServiceName != ''
        GROUP BY OrgId, Hour, ServiceName, DbSystem, DeploymentEnv, QueryKey;

CREATE MATERIALIZED VIEW IF NOT EXISTS service_map_spans_mv TO service_map_spans AS
SELECT
          OrgId,
          toDateTime(Timestamp) AS Timestamp,
          TraceId,
          SpanId,
          ParentSpanId,
          ServiceName,
          SpanKind,
          Duration,
          StatusCode,
          TraceState,
          ResourceAttributes['deployment.environment'] AS DeploymentEnv
        FROM traces
        WHERE SpanKind IN ('Client', 'Producer', 'Server', 'Consumer');

CREATE MATERIALIZED VIEW IF NOT EXISTS service_overview_spans_mv TO service_overview_spans AS
SELECT
          OrgId,
          toDateTime(Timestamp) AS Timestamp,
          ServiceName,
          Duration,
          StatusCode,
          TraceState,
          ResourceAttributes['deployment.environment'] AS DeploymentEnv,
          ResourceAttributes['deployment.commit_sha'] AS CommitSha,
          SampleRate,
          ResourceAttributes['service.namespace'] AS ServiceNamespace
        FROM traces
        WHERE SpanKind IN ('Server', 'Consumer') OR ParentSpanId = '';

CREATE MATERIALIZED VIEW IF NOT EXISTS service_platforms_hourly_mv TO service_platforms_hourly AS
SELECT
          OrgId,
          toStartOfHour(toDateTime(Timestamp)) AS Hour,
          ServiceName,
          ResourceAttributes['deployment.environment'] AS DeploymentEnv,
          max(ResourceAttributes['k8s.cluster.name']) AS K8sCluster,
          max(ResourceAttributes['k8s.pod.name']) AS K8sPodName,
          max(ResourceAttributes['k8s.deployment.name']) AS K8sDeploymentName,
          max(ResourceAttributes['k8s.statefulset.name']) AS K8sStatefulSetName,
          max(ResourceAttributes['k8s.daemonset.name']) AS K8sDaemonSetName,
          max(ResourceAttributes['k8s.namespace.name']) AS K8sNamespaceName,
          max(ResourceAttributes['cloud.platform']) AS CloudPlatform,
          max(ResourceAttributes['cloud.provider']) AS CloudProvider,
          max(ResourceAttributes['faas.name']) AS FaasName,
          max(ResourceAttributes['maple.sdk.type']) AS MapleSdkType,
          max(ResourceAttributes['process.runtime.name']) AS ProcessRuntimeName,
          count() AS SpanCount
        FROM traces
        WHERE ServiceName != ''
        GROUP BY OrgId, Hour, ServiceName, DeploymentEnv;

CREATE MATERIALIZED VIEW IF NOT EXISTS service_usage_logs_mv TO service_usage AS
SELECT
          OrgId,
          ServiceName,
          toStartOfHour(TimestampTime) AS Hour,
          count() AS LogCount,
          sum(length(Body) + 200) AS LogSizeBytes,
          0 AS TraceCount,
          0 AS TraceSizeBytes,
          0 AS SumMetricCount,
          0 AS SumMetricSizeBytes,
          0 AS GaugeMetricCount,
          0 AS GaugeMetricSizeBytes,
          0 AS HistogramMetricCount,
          0 AS HistogramMetricSizeBytes,
          0 AS ExpHistogramMetricCount,
          0 AS ExpHistogramMetricSizeBytes
        FROM logs
        GROUP BY OrgId, ServiceName, Hour;

CREATE MATERIALIZED VIEW IF NOT EXISTS service_usage_metrics_exp_histogram_mv TO service_usage AS
SELECT
          OrgId,
          ServiceName,
          toStartOfHour(toDateTime(TimeUnix)) AS Hour,
          0 AS LogCount,
          0 AS LogSizeBytes,
          0 AS TraceCount,
          0 AS TraceSizeBytes,
          0 AS SumMetricCount,
          0 AS SumMetricSizeBytes,
          0 AS GaugeMetricCount,
          0 AS GaugeMetricSizeBytes,
          0 AS HistogramMetricCount,
          0 AS HistogramMetricSizeBytes,
          count() AS ExpHistogramMetricCount,
          count() * 300 AS ExpHistogramMetricSizeBytes
        FROM metrics_exponential_histogram
        GROUP BY OrgId, ServiceName, Hour;

CREATE MATERIALIZED VIEW IF NOT EXISTS service_usage_metrics_gauge_mv TO service_usage AS
SELECT
          OrgId,
          ServiceName,
          toStartOfHour(toDateTime(TimeUnix)) AS Hour,
          0 AS LogCount,
          0 AS LogSizeBytes,
          0 AS TraceCount,
          0 AS TraceSizeBytes,
          0 AS SumMetricCount,
          0 AS SumMetricSizeBytes,
          count() AS GaugeMetricCount,
          count() * 150 AS GaugeMetricSizeBytes,
          0 AS HistogramMetricCount,
          0 AS HistogramMetricSizeBytes,
          0 AS ExpHistogramMetricCount,
          0 AS ExpHistogramMetricSizeBytes
        FROM metrics_gauge
        GROUP BY OrgId, ServiceName, Hour;

CREATE MATERIALIZED VIEW IF NOT EXISTS service_usage_metrics_histogram_mv TO service_usage AS
SELECT
          OrgId,
          ServiceName,
          toStartOfHour(toDateTime(TimeUnix)) AS Hour,
          0 AS LogCount,
          0 AS LogSizeBytes,
          0 AS TraceCount,
          0 AS TraceSizeBytes,
          0 AS SumMetricCount,
          0 AS SumMetricSizeBytes,
          0 AS GaugeMetricCount,
          0 AS GaugeMetricSizeBytes,
          count() AS HistogramMetricCount,
          count() * 250 AS HistogramMetricSizeBytes,
          0 AS ExpHistogramMetricCount,
          0 AS ExpHistogramMetricSizeBytes
        FROM metrics_histogram
        GROUP BY OrgId, ServiceName, Hour;

CREATE MATERIALIZED VIEW IF NOT EXISTS service_usage_metrics_sum_mv TO service_usage AS
SELECT
          OrgId,
          ServiceName,
          toStartOfHour(toDateTime(TimeUnix)) AS Hour,
          0 AS LogCount,
          0 AS LogSizeBytes,
          0 AS TraceCount,
          0 AS TraceSizeBytes,
          count() AS SumMetricCount,
          count() * 150 AS SumMetricSizeBytes,
          0 AS GaugeMetricCount,
          0 AS GaugeMetricSizeBytes,
          0 AS HistogramMetricCount,
          0 AS HistogramMetricSizeBytes,
          0 AS ExpHistogramMetricCount,
          0 AS ExpHistogramMetricSizeBytes
        FROM metrics_sum
        GROUP BY OrgId, ServiceName, Hour;

CREATE MATERIALIZED VIEW IF NOT EXISTS service_usage_traces_mv TO service_usage AS
SELECT
          OrgId,
          ServiceName,
          toStartOfHour(toDateTime(Timestamp)) AS Hour,
          0 AS LogCount,
          0 AS LogSizeBytes,
          count() AS TraceCount,
          sum(length(SpanName) + 300) AS TraceSizeBytes,
          0 AS SumMetricCount,
          0 AS SumMetricSizeBytes,
          0 AS GaugeMetricCount,
          0 AS GaugeMetricSizeBytes,
          0 AS HistogramMetricCount,
          0 AS HistogramMetricSizeBytes,
          0 AS ExpHistogramMetricCount,
          0 AS ExpHistogramMetricSizeBytes
        FROM traces
        GROUP BY OrgId, ServiceName, Hour;

CREATE MATERIALIZED VIEW IF NOT EXISTS span_metrics_calls_hourly_mv TO span_metrics_calls_hourly AS
SELECT
          OrgId,
          toStartOfHour(toDateTime(TimeUnix)) AS Hour,
          ServiceName,
          MetricName,
          Attributes['span.kind'] AS SpanKind,
          cityHash64(mapKeys(Attributes), mapValues(Attributes)) AS AttrFingerprint,
          cityHash64(mapKeys(ResourceAttributes), mapValues(ResourceAttributes)) AS ResourceFingerprint,
          StartTimeUnix,
          argMaxState(Value, TimeUnix) AS LastValue
        FROM metrics_sum
        WHERE MetricName IN ('span.metrics.calls', 'calls') AND IsMonotonic
        GROUP BY OrgId, Hour, ServiceName, MetricName, SpanKind, AttrFingerprint, ResourceFingerprint, StartTimeUnix;

CREATE MATERIALIZED VIEW IF NOT EXISTS trace_detail_spans_mv TO trace_detail_spans AS
SELECT
          OrgId,
          Timestamp,
          TraceId,
          SpanId,
          ParentSpanId,
          SpanName,
          SpanKind,
          ServiceName,
          Duration,
          StatusCode,
          StatusMessage,
          SpanAttributes,
          ResourceAttributes,
          EventsTimestamp,
          EventsName,
          EventsAttributes
        FROM traces;

CREATE MATERIALIZED VIEW IF NOT EXISTS trace_list_mv_mv TO trace_list_mv AS
SELECT
          OrgId,
          TraceId,
          toDateTime(Timestamp) AS Timestamp,
          ServiceName,
          if(
            (SpanName LIKE 'http.server %' OR SpanName IN ('GET','POST','PUT','PATCH','DELETE','HEAD','OPTIONS'))
            AND (SpanAttributes['http.route'] != '' OR SpanAttributes['url.path'] != ''),
            concat(
              if(SpanName LIKE 'http.server %', replaceOne(SpanName, 'http.server ', ''), SpanName),
              ' ',
              if(SpanAttributes['http.route'] != '', SpanAttributes['http.route'], SpanAttributes['url.path'])
            ),
            SpanName
          ) AS SpanName,
          SpanKind,
          Duration,
          StatusCode,
          if(SpanAttributes['http.method'] != '', SpanAttributes['http.method'], SpanAttributes['http.request.method']) AS HttpMethod,
          if(SpanAttributes['http.route'] != '', SpanAttributes['http.route'], if(SpanAttributes['url.path'] != '', SpanAttributes['url.path'], SpanAttributes['http.target'])) AS HttpRoute,
          if(SpanAttributes['http.status_code'] != '', SpanAttributes['http.status_code'], SpanAttributes['http.response.status_code']) AS HttpStatusCode,
          ResourceAttributes['deployment.environment'] AS DeploymentEnv,
          toUInt8(
            StatusCode = 'Error'
            OR (SpanAttributes['http.status_code'] != '' AND toUInt16OrZero(SpanAttributes['http.status_code']) >= 500)
            OR (SpanAttributes['http.response.status_code'] != '' AND toUInt16OrZero(SpanAttributes['http.response.status_code']) >= 500)
          ) AS HasError,
          TraceState,
          ResourceAttributes['service.namespace'] AS ServiceNamespace
        FROM traces
        WHERE ParentSpanId = '';

CREATE MATERIALIZED VIEW IF NOT EXISTS trace_resource_attribute_keys_mv TO attribute_keys_hourly AS
SELECT
          OrgId,
          toStartOfHour(toDateTime(Timestamp)) AS Hour,
          arrayJoin(mapKeys(ResourceAttributes)) AS AttributeKey,
          'resource' AS AttributeScope,
          count() AS UsageCount
        FROM traces
        WHERE ResourceAttributes != map()
        GROUP BY OrgId, Hour, AttributeKey, AttributeScope;

CREATE MATERIALIZED VIEW IF NOT EXISTS trace_resource_attribute_values_mv TO attribute_values_hourly AS
SELECT
          OrgId,
          toStartOfHour(toDateTime(Timestamp)) AS Hour,
          AttributeKey,
          AttributeValue,
          'resource' AS AttributeScope,
          count() AS UsageCount
        FROM traces
        ARRAY JOIN
          mapKeys(ResourceAttributes) AS AttributeKey,
          mapValues(ResourceAttributes) AS AttributeValue
        WHERE AttributeValue != ''
        GROUP BY OrgId, Hour, AttributeKey, AttributeValue, AttributeScope;

CREATE MATERIALIZED VIEW IF NOT EXISTS trace_span_attribute_keys_mv TO attribute_keys_hourly AS
SELECT
          OrgId,
          toStartOfHour(toDateTime(Timestamp)) AS Hour,
          arrayJoin(mapKeys(SpanAttributes)) AS AttributeKey,
          'span' AS AttributeScope,
          count() AS UsageCount
        FROM traces
        WHERE SpanAttributes != map()
        GROUP BY OrgId, Hour, AttributeKey, AttributeScope;

CREATE MATERIALIZED VIEW IF NOT EXISTS trace_span_attribute_values_mv TO attribute_values_hourly AS
SELECT
          OrgId,
          toStartOfHour(toDateTime(Timestamp)) AS Hour,
          AttributeKey,
          AttributeValue,
          'span' AS AttributeScope,
          count() AS UsageCount
        FROM traces
        ARRAY JOIN
          mapKeys(SpanAttributes) AS AttributeKey,
          mapValues(SpanAttributes) AS AttributeValue
        WHERE AttributeValue != ''
        GROUP BY OrgId, Hour, AttributeKey, AttributeValue, AttributeScope;

CREATE MATERIALIZED VIEW IF NOT EXISTS traces_aggregates_hourly_mv TO traces_aggregates_hourly AS
SELECT
          OrgId,
          toStartOfHour(toDateTime(Timestamp)) AS Hour,
          ServiceName,
          SpanName,
          SpanKind,
          StatusCode,
          IsEntryPoint,
          ResourceAttributes['deployment.environment'] AS DeploymentEnv,
          sum(SampleRate) AS WeightedCount,
          sum(toFloat64(Duration) * SampleRate) AS WeightedDurationSum,
          sumIf(SampleRate, StatusCode = 'Error') AS WeightedErrorCount,
          quantilesTDigestWeightedState(0.5, 0.95, 0.99)(Duration, toUInt32(SampleRate)) AS DurationQuantiles,
          min(Duration) AS DurationMin,
          max(Duration) AS DurationMax
        FROM traces
        GROUP BY OrgId, Hour, ServiceName, SpanName, SpanKind, StatusCode, IsEntryPoint, DeploymentEnv;
