{{- if .Values.agent.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "maple-k8s-infra.agent.fullname" . }}
  labels:
    {{- include "maple-k8s-infra.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "nodes", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes/stats", "nodes/proxy", "nodes/pods"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "maple-k8s-infra.agent.fullname" . }}
  labels:
    {{- include "maple-k8s-infra.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "maple-k8s-infra.agent.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "maple-k8s-infra.agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
