{{- if and .Values.maple.ingestKey.value (not .Values.maple.ingestKey.existingSecret.name) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "maple-k8s-infra.ingestSecretName" . }}
  labels:
    {{- include "maple-k8s-infra.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "maple-k8s-infra.ingestSecretKey" . }}: {{ .Values.maple.ingestKey.value | quote }}
{{- end -}}
{{- if and .Values.maple.tinybirdExport.enabled .Values.maple.tinybirdExport.token.value (not .Values.maple.tinybirdExport.token.existingSecret.name) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "maple-k8s-infra.tinybirdSecretName" . }}
  labels:
    {{- include "maple-k8s-infra.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "maple-k8s-infra.tinybirdSecretKey" . }}: {{ .Values.maple.tinybirdExport.token.value | quote }}
{{- end -}}
{{- if and .Values.maple.clickhouseExport.enabled .Values.maple.clickhouseExport.password.value (not .Values.maple.clickhouseExport.password.existingSecret.name) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "maple-k8s-infra.clickhouseSecretName" . }}
  labels:
    {{- include "maple-k8s-infra.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "maple-k8s-infra.clickhouseSecretKey" . }}: {{ .Values.maple.clickhouseExport.password.value | quote }}
{{- end -}}
