import { writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join } from "node:path"

const MIN_INTERVAL_SECONDS = 5
const MAX_INTERVAL_SECONDS = 300
const DISCOVERY_REFRESH_INTERVAL = "30s"

const scrapeTimeout = (intervalSeconds: number): string => {
	const timeoutSeconds = Math.min(10, Math.max(1, intervalSeconds - 1))
	return `${timeoutSeconds}s`
}

const scrapeJob = (intervalSeconds: number): string => `                - job_name: "maple-managed-scrape-${intervalSeconds}s"
                  scrape_interval: ${intervalSeconds}s
                  scrape_timeout: ${scrapeTimeout(intervalSeconds)}
                  authorization:
                      credentials: "\${env:SD_INTERNAL_TOKEN}"
                  http_sd_configs:
                      - url: "http://\${env:SD_API_HOST}:\${env:SD_API_PORT}/api/internal/sd/prometheus?interval=${intervalSeconds}"
                        authorization:
                            credentials: "\${env:SD_INTERNAL_TOKEN}"
                        refresh_interval: ${DISCOVERY_REFRESH_INTERVAL}`

const scrapeJobs = Array.from(
	{ length: MAX_INTERVAL_SECONDS - MIN_INTERVAL_SECONDS + 1 },
	(_, index) => scrapeJob(MIN_INTERVAL_SECONDS + index),
).join("\n")

const collectorConfig = `# OpenTelemetry Collector Configuration
# Configured for internal OTLP ingest forwarding to Tinybird
# The Prometheus scrape jobs are generated by otel/generate-prometheus-scrape-config.ts.

receivers:
    otlp:
        protocols:
            grpc:
                endpoint: 0.0.0.0:4317
            http:
                endpoint: 0.0.0.0:4318

    prometheus:
        config:
            scrape_configs:
${scrapeJobs}

processors:
    batch:
        timeout: 1s
        send_batch_size: 5000
        send_batch_max_size: 10000

    memory_limiter:
        check_interval: 1s
        limit_mib: 512
        spike_limit_mib: 128

    groupbyattrs/prometheus:
        keys:
            - maple_org_id

    resource/prometheus:
        attributes:
            - key: maple_ingest_source
              value: "prometheus-scrape"
              action: upsert
            - key: maple_ingest_key_type
              value: "internal"
              action: upsert

exporters:
    tinybird:
        endpoint: \${env:TINYBIRD_HOST}
        token: \${env:TINYBIRD_TOKEN}
        timeout: 30s
        metrics:
            sum:
                datasource: metrics_sum
            gauge:
                datasource: metrics_gauge
            histogram:
                datasource: metrics_histogram
            exponential_histogram:
                datasource: metrics_exponential_histogram
        retry_on_failure:
            enabled: true
            initial_interval: 1s
            max_interval: 30s
            max_elapsed_time: 300s
        sending_queue:
            enabled: true
            num_consumers: 8
            queue_size: 10000
            storage: file_storage/queue

extensions:
    file_storage/queue:
        directory: /var/lib/otelcol/file_storage
        create_directory: true
        timeout: 10s
        compaction:
            on_start: true
            on_rebound: true

    health_check:
        endpoint: 0.0.0.0:13133

    zpages:
        endpoint: 0.0.0.0:55679

service:
    extensions: [health_check, zpages, file_storage/queue]

    pipelines:
        logs:
            receivers: [otlp]
            processors: [memory_limiter, batch]
            exporters: [tinybird]

        traces:
            receivers: [otlp]
            processors: [memory_limiter, batch]
            exporters: [tinybird]

        metrics:
            receivers: [otlp]
            processors: [memory_limiter, batch]
            exporters: [tinybird]

        metrics/prometheus:
            receivers: [prometheus]
            processors: [memory_limiter, groupbyattrs/prometheus, resource/prometheus, batch]
            exporters: [tinybird]

    telemetry:
        logs:
            level: info
`

const __dirname = dirname(fileURLToPath(import.meta.url))
writeFileSync(join(__dirname, "collector-config.yaml"), collectorConfig)
