// Inline apps/local-ui/dist into apps/cli/src/server/ui-embed.gen.ts so
// `bun build --compile` bakes the SPA into the `maple` binary. Run by
// scripts/build-local-binary.sh, which restores the committed stub afterwards.

import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs"
import { join, relative } from "node:path"
import { fileURLToPath } from "node:url"

const distDir = fileURLToPath(new URL("../apps/local-ui/dist/", import.meta.url))
const outPath = fileURLToPath(new URL("../apps/cli/src/server/ui-embed.gen.ts", import.meta.url))

const MIME: Record<string, string> = {
	html: "text/html",
	js: "text/javascript",
	mjs: "text/javascript",
	css: "text/css",
	json: "application/json",
	map: "application/json",
	svg: "image/svg+xml",
	png: "image/png",
	jpg: "image/jpeg",
	jpeg: "image/jpeg",
	gif: "image/gif",
	webp: "image/webp",
	ico: "image/x-icon",
	woff: "font/woff",
	woff2: "font/woff2",
	ttf: "font/ttf",
	txt: "text/plain",
	wasm: "application/wasm",
}
const mimeFor = (p: string): string => MIME[p.split(".").pop()?.toLowerCase() ?? ""] ?? "application/octet-stream"

function* walk(dir: string): Generator<string> {
	for (const entry of readdirSync(dir)) {
		const full = join(dir, entry)
		if (statSync(full).isDirectory()) yield* walk(full)
		else yield full
	}
}

const entries: string[] = []
let count = 0
for (const file of walk(distDir)) {
	const rel = relative(distDir, file).split("\\").join("/")
	const b64 = readFileSync(file).toString("base64")
	entries.push(`\t[${JSON.stringify(rel)}, { data: d(${JSON.stringify(b64)}), contentType: ${JSON.stringify(mimeFor(rel))} }],`)
	count++
}

const out = `// AUTO-GENERATED by scripts/gen-ui-embed.ts during the local-binary build.
// Do not edit; do not commit (the committed version is the dev stub).
export interface EmbeddedAsset {
	readonly data: Uint8Array
	readonly contentType: string
}
const d = (b64: string): Uint8Array => Uint8Array.from(Buffer.from(b64, "base64"))
export const embeddedAssets: ReadonlyMap<string, EmbeddedAsset> | undefined = new Map<string, EmbeddedAsset>([
${entries.join("\n")}
])
`

writeFileSync(outPath, out)
console.log(`Embedded ${count} SPA file(s) into ${outPath}`)
