import { mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname } from "node:path"
import { fileURLToPath } from "node:url"
import { latestSnapshotStatements, projectRevision } from "../packages/domain/src/generated/clickhouse-schema"

const outputPath = fileURLToPath(new URL("../apps/cli/src/server/schema/local-schema.sql", import.meta.url))
const checkMode = process.argv.includes("--check")

const rendered = render(latestSnapshotStatements, projectRevision)
let existing = ""

try {
	existing = readFileSync(outputPath, "utf8")
} catch {
	existing = ""
}

if (checkMode) {
	if (existing !== rendered) {
		console.error("local-schema.sql is out of date. Run `bun run clickhouse:schema`.")
		process.exit(1)
	}
	console.log(
		`local-schema.sql is up to date (${projectRevision}, ${latestSnapshotStatements.length} statements).`,
	)
} else {
	mkdirSync(dirname(outputPath), { recursive: true })
	writeFileSync(outputPath, rendered)
	console.log(
		`Wrote local-schema.sql (${projectRevision}, ${latestSnapshotStatements.length} statements) to ${outputPath}.`,
	)
}

function render(stmts: ReadonlyArray<string>, revision: string): string {
	const header = [
		"-- This file is generated by scripts/generate-clickhouse-schema-sql.ts",
		"-- Do not edit manually. Run `bun run clickhouse:schema` to regenerate.",
		`-- projectRevision: ${revision}`,
		"",
		"",
	].join("\n")
	const body = stmts.map((s) => `${s};`).join("\n\n")
	return `${header}${body}\n`
}
