import { mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname } from "node:path"
import { fileURLToPath } from "node:url"
import { emitProjectDdl } from "../packages/domain/src/clickhouse/ddl-emitter"
import { buildTinybirdProjectManifest } from "../packages/domain/src/tinybird/project-manifest"

const outputPath = fileURLToPath(
	new URL("../packages/domain/src/generated/clickhouse-schema.ts", import.meta.url),
)
const checkMode = process.argv.includes("--check")

const manifest = await buildTinybirdProjectManifest()
const statements = emitProjectDdl(manifest)

const renderedModule = renderModule(statements, manifest.projectRevision)
let existingModule = ""

try {
	existingModule = readFileSync(outputPath, "utf8")
} catch {
	existingModule = ""
}

if (checkMode) {
	if (existingModule !== renderedModule) {
		console.error(
			"ClickHouse schema is out of date. Run `bun run clickhouse:schema`.",
		)
		process.exit(1)
	}
	console.log(
		`ClickHouse schema is up to date (${manifest.projectRevision}, ${statements.length} statements).`,
	)
} else {
	mkdirSync(dirname(outputPath), { recursive: true })
	writeFileSync(outputPath, renderedModule)
	console.log(
		`Wrote ClickHouse schema (${manifest.projectRevision}, ${statements.length} statements) to ${outputPath}.`,
	)
}

function renderModule(stmts: ReadonlyArray<string>, revision: string): string {
	const body = stmts.map((s) => JSON.stringify(s)).join(",\n\t")
	return `// This file is generated by scripts/generate-clickhouse-schema.ts
// Do not edit manually.

export const projectRevision = ${JSON.stringify(revision)} as const

export const latestSnapshotStatements: ReadonlyArray<string> = [
\t${body},
] as const
`
}
