// This file is generated by scripts/generate-clickhouse-insert-mappings.ts
// Do not edit manually.

pub const PROJECT_REVISION: &str = "019c3db4cf690e3748b302098cae4c9213d18c55355db9fc68ea44982c7a980a";
// Gate for BYO-ClickHouse ingest readiness — the migration version, NOT the
// Tinybird-coupled PROJECT_REVISION. Compared against
// org_clickhouse_settings.schema_version. See @maple/domain/clickhouse
// clickHouseSchemaVersion.
pub const SCHEMA_VERSION: &str = "4";
pub const ORG_PLACEHOLDER: &str = "__ORG__";

#[derive(Debug)]
pub struct InsertMapping {
    pub datasource: &'static str,
    pub table: &'static str,
    pub columns: &'static [&'static str],
    pub selects: &'static [&'static str],
    pub input_schema: &'static str,
}

pub const DATASOURCES: &[InsertMapping] = &[
    InsertMapping {
        datasource: "traces",
        table: "traces",
        columns: &["OrgId", "Timestamp", "TraceId", "SpanId", "ParentSpanId", "TraceState", "SpanName", "SpanKind", "ServiceName", "ResourceSchemaUrl", "ResourceAttributes", "ScopeSchemaUrl", "ScopeName", "ScopeVersion", "ScopeAttributes", "Duration", "StatusCode", "StatusMessage", "SpanAttributes", "EventsTimestamp", "EventsName", "EventsAttributes", "LinksTraceId", "LinksSpanId", "LinksTraceState", "LinksAttributes"],
        selects: &["__ORG__", "start_time", "trace_id", "span_id", "parent_span_id", "trace_state", "span_name", "span_kind", "service_name", "resource_schema_url", "resource_attributes", "scope_schema_url", "scope_name", "scope_version", "scope_attributes", "duration", "status_code", "status_message", "span_attributes", "events_timestamp", "events_name", "events_attributes", "links_trace_id", "links_span_id", "links_trace_state", "links_attributes"],
        input_schema: "start_time DateTime64(9), trace_id String, span_id String, parent_span_id String, trace_state String, span_name LowCardinality(String), span_kind LowCardinality(String), service_name LowCardinality(String), resource_schema_url String, resource_attributes Map(LowCardinality(String), String), scope_schema_url String, scope_name String, scope_version String, scope_attributes Map(LowCardinality(String), String), duration UInt64, status_code LowCardinality(String), status_message String, span_attributes Map(LowCardinality(String), String), events_timestamp Array(DateTime64(9)), events_name Array(LowCardinality(String)), events_attributes Array(Map(LowCardinality(String), String)), links_trace_id Array(String), links_span_id Array(String), links_trace_state Array(String), links_attributes Array(Map(LowCardinality(String), String))",
    },
    InsertMapping {
        datasource: "logs",
        table: "logs",
        columns: &["OrgId", "Timestamp", "TimestampTime", "TraceId", "SpanId", "TraceFlags", "SeverityText", "SeverityNumber", "ServiceName", "Body", "ResourceSchemaUrl", "ResourceAttributes", "ScopeSchemaUrl", "ScopeName", "ScopeVersion", "ScopeAttributes", "LogAttributes"],
        selects: &["__ORG__", "timestamp", "timestamp", "trace_id", "span_id", "flags", "severity_text", "severity_number", "service_name", "body", "resource_schema_url", "resource_attributes", "scope_schema_url", "scope_name", "scope_version", "scope_attributes", "log_attributes"],
        input_schema: "timestamp DateTime64(9), trace_id String, span_id String, flags UInt8, severity_text LowCardinality(String), severity_number UInt8, service_name LowCardinality(String), body String, resource_schema_url String, resource_attributes Map(LowCardinality(String), String), scope_schema_url String, scope_name String, scope_version String, scope_attributes Map(LowCardinality(String), String), log_attributes Map(LowCardinality(String), String)",
    },
    InsertMapping {
        datasource: "metrics_sum",
        table: "metrics_sum",
        columns: &["OrgId", "ResourceAttributes", "ResourceSchemaUrl", "ScopeName", "ScopeVersion", "ScopeAttributes", "ScopeSchemaUrl", "ServiceName", "MetricName", "MetricDescription", "MetricUnit", "Attributes", "StartTimeUnix", "TimeUnix", "Value", "Flags", "ExemplarsTraceId", "ExemplarsSpanId", "ExemplarsTimestamp", "ExemplarsValue", "ExemplarsFilteredAttributes", "AggregationTemporality", "IsMonotonic"],
        selects: &["__ORG__", "resource_attributes", "resource_schema_url", "scope_name", "scope_version", "scope_attributes", "scope_schema_url", "service_name", "metric_name", "metric_description", "metric_unit", "metric_attributes", "start_timestamp", "timestamp", "value", "flags", "exemplars_trace_id", "exemplars_span_id", "exemplars_timestamp", "exemplars_value", "exemplars_filtered_attributes", "aggregation_temporality", "is_monotonic"],
        input_schema: "resource_attributes Map(LowCardinality(String), String), resource_schema_url String, scope_name String, scope_version String, scope_attributes Map(LowCardinality(String), String), scope_schema_url String, service_name LowCardinality(String), metric_name LowCardinality(String), metric_description LowCardinality(String), metric_unit LowCardinality(String), metric_attributes Map(LowCardinality(String), String), start_timestamp DateTime64(9), timestamp DateTime64(9), value Float64, flags UInt32, exemplars_trace_id Array(String), exemplars_span_id Array(String), exemplars_timestamp Array(DateTime64(9)), exemplars_value Array(Float64), exemplars_filtered_attributes Array(Map(LowCardinality(String), String)), aggregation_temporality Int32, is_monotonic Bool",
    },
    InsertMapping {
        datasource: "metrics_gauge",
        table: "metrics_gauge",
        columns: &["OrgId", "ResourceAttributes", "ResourceSchemaUrl", "ScopeName", "ScopeVersion", "ScopeAttributes", "ScopeSchemaUrl", "ServiceName", "MetricName", "MetricDescription", "MetricUnit", "Attributes", "StartTimeUnix", "TimeUnix", "Value", "Flags", "ExemplarsTraceId", "ExemplarsSpanId", "ExemplarsTimestamp", "ExemplarsValue", "ExemplarsFilteredAttributes"],
        selects: &["__ORG__", "resource_attributes", "resource_schema_url", "scope_name", "scope_version", "scope_attributes", "scope_schema_url", "service_name", "metric_name", "metric_description", "metric_unit", "metric_attributes", "start_timestamp", "timestamp", "value", "flags", "exemplars_trace_id", "exemplars_span_id", "exemplars_timestamp", "exemplars_value", "exemplars_filtered_attributes"],
        input_schema: "resource_attributes Map(LowCardinality(String), String), resource_schema_url String, scope_name String, scope_version String, scope_attributes Map(LowCardinality(String), String), scope_schema_url String, service_name LowCardinality(String), metric_name LowCardinality(String), metric_description LowCardinality(String), metric_unit LowCardinality(String), metric_attributes Map(LowCardinality(String), String), start_timestamp DateTime64(9), timestamp DateTime64(9), value Float64, flags UInt32, exemplars_trace_id Array(String), exemplars_span_id Array(String), exemplars_timestamp Array(DateTime64(9)), exemplars_value Array(Float64), exemplars_filtered_attributes Array(Map(LowCardinality(String), String))",
    },
    InsertMapping {
        datasource: "metrics_histogram",
        table: "metrics_histogram",
        columns: &["OrgId", "ResourceAttributes", "ResourceSchemaUrl", "ScopeName", "ScopeVersion", "ScopeAttributes", "ScopeSchemaUrl", "ServiceName", "MetricName", "MetricDescription", "MetricUnit", "Attributes", "StartTimeUnix", "TimeUnix", "Count", "Sum", "BucketCounts", "ExplicitBounds", "ExemplarsTraceId", "ExemplarsSpanId", "ExemplarsTimestamp", "ExemplarsValue", "ExemplarsFilteredAttributes", "Flags", "Min", "Max", "AggregationTemporality"],
        selects: &["__ORG__", "resource_attributes", "resource_schema_url", "scope_name", "scope_version", "scope_attributes", "scope_schema_url", "service_name", "metric_name", "metric_description", "metric_unit", "metric_attributes", "start_timestamp", "timestamp", "count", "sum", "bucket_counts", "explicit_bounds", "exemplars_trace_id", "exemplars_span_id", "exemplars_timestamp", "exemplars_value", "exemplars_filtered_attributes", "flags", "min", "max", "aggregation_temporality"],
        input_schema: "resource_attributes Map(LowCardinality(String), String), resource_schema_url String, scope_name String, scope_version String, scope_attributes Map(LowCardinality(String), String), scope_schema_url String, service_name LowCardinality(String), metric_name LowCardinality(String), metric_description LowCardinality(String), metric_unit LowCardinality(String), metric_attributes Map(LowCardinality(String), String), start_timestamp DateTime64(9), timestamp DateTime64(9), count UInt64, sum Float64, bucket_counts Array(UInt64), explicit_bounds Array(Float64), exemplars_trace_id Array(String), exemplars_span_id Array(String), exemplars_timestamp Array(DateTime64(9)), exemplars_value Array(Float64), exemplars_filtered_attributes Array(Map(LowCardinality(String), String)), flags UInt32, min Nullable(Float64), max Nullable(Float64), aggregation_temporality Int32",
    },
    InsertMapping {
        datasource: "metrics_exponential_histogram",
        table: "metrics_exponential_histogram",
        columns: &["OrgId", "ResourceAttributes", "ResourceSchemaUrl", "ScopeName", "ScopeVersion", "ScopeAttributes", "ScopeSchemaUrl", "ServiceName", "MetricName", "MetricDescription", "MetricUnit", "Attributes", "StartTimeUnix", "TimeUnix", "Count", "Sum", "Scale", "ZeroCount", "PositiveOffset", "PositiveBucketCounts", "NegativeOffset", "NegativeBucketCounts", "ExemplarsTraceId", "ExemplarsSpanId", "ExemplarsTimestamp", "ExemplarsValue", "ExemplarsFilteredAttributes", "Flags", "Min", "Max", "AggregationTemporality"],
        selects: &["__ORG__", "resource_attributes", "resource_schema_url", "scope_name", "scope_version", "scope_attributes", "scope_schema_url", "service_name", "metric_name", "metric_description", "metric_unit", "metric_attributes", "start_timestamp", "timestamp", "count", "sum", "scale", "zero_count", "positive_offset", "positive_bucket_counts", "negative_offset", "negative_bucket_counts", "exemplars_trace_id", "exemplars_span_id", "exemplars_timestamp", "exemplars_value", "exemplars_filtered_attributes", "flags", "min", "max", "aggregation_temporality"],
        input_schema: "resource_attributes Map(LowCardinality(String), String), resource_schema_url String, scope_name String, scope_version String, scope_attributes Map(LowCardinality(String), String), scope_schema_url String, service_name LowCardinality(String), metric_name LowCardinality(String), metric_description LowCardinality(String), metric_unit LowCardinality(String), metric_attributes Map(LowCardinality(String), String), start_timestamp DateTime64(9), timestamp DateTime64(9), count UInt64, sum Float64, scale Int32, zero_count UInt64, positive_offset Int32, positive_bucket_counts Array(UInt64), negative_offset Int32, negative_bucket_counts Array(UInt64), exemplars_trace_id Array(String), exemplars_span_id Array(String), exemplars_timestamp Array(DateTime64(9)), exemplars_value Array(Float64), exemplars_filtered_attributes Array(Map(LowCardinality(String), String)), flags UInt32, min Nullable(Float64), max Nullable(Float64), aggregation_temporality Int32",
    },
    InsertMapping {
        datasource: "session_replays",
        table: "session_replays",
        columns: &["OrgId", "SessionId", "StartTime", "EndTime", "DurationMs", "Status", "UserId", "UrlInitial", "UserAgent", "BrowserName", "OsName", "DeviceType", "Country", "ServiceName", "PageViews", "ClickCount", "ErrorCount", "TraceIds", "ResourceAttributes", "Version"],
        selects: &["__ORG__", "session_id", "start_time", "end_time", "duration_ms", "status", "user_id", "url_initial", "user_agent", "browser_name", "os_name", "device_type", "country", "service_name", "page_views", "click_count", "error_count", "trace_ids", "resource_attributes", "version"],
        input_schema: "session_id String, start_time DateTime64(9), end_time Nullable(DateTime64(9)), duration_ms Nullable(UInt32), status LowCardinality(String), user_id String, url_initial String, user_agent String, browser_name LowCardinality(String), os_name LowCardinality(String), device_type LowCardinality(String), country LowCardinality(String), service_name LowCardinality(String), page_views UInt32, click_count UInt32, error_count UInt32, trace_ids Array(String), resource_attributes Map(LowCardinality(String), String), version UInt32",
    },
    InsertMapping {
        datasource: "session_replay_events",
        table: "session_replay_events",
        columns: &["OrgId", "SessionId", "ChunkSeq", "Timestamp", "DurationMs", "EventCount", "ByteSize", "Events", "IsCheckpoint"],
        selects: &["__ORG__", "session_id", "chunk_seq", "timestamp", "duration_ms", "event_count", "byte_size", "events", "is_checkpoint"],
        input_schema: "session_id String, chunk_seq UInt32, timestamp DateTime64(9), duration_ms UInt32, event_count UInt32, byte_size UInt32, events String, is_checkpoint UInt8",
    },
    InsertMapping {
        datasource: "session_events",
        table: "session_events",
        columns: &["OrgId", "SessionId", "Timestamp", "Seq", "Type", "Url", "TraceId", "Level", "Message", "TargetSelector", "TargetText", "NetMethod", "NetUrl", "NetStatus", "NetDurationMs", "ErrorStack", "Attributes"],
        selects: &["__ORG__", "session_id", "timestamp", "seq", "type", "url", "trace_id", "level", "message", "target_selector", "target_text", "net_method", "net_url", "net_status", "net_duration_ms", "error_stack", "attributes"],
        input_schema: "session_id String, timestamp DateTime64(9), seq UInt32, type LowCardinality(String), url String, trace_id String, level LowCardinality(String), message String, target_selector String, target_text String, net_method LowCardinality(String), net_url String, net_status UInt16, net_duration_ms UInt32, error_stack String, attributes Map(LowCardinality(String), String)",
    },
];

pub fn mapping_for(datasource: &str) -> Option<&'static InsertMapping> {
    match datasource {
        "traces" => Some(&DATASOURCES[0]),
        "logs" => Some(&DATASOURCES[1]),
        "metrics_sum" => Some(&DATASOURCES[2]),
        "metrics_gauge" => Some(&DATASOURCES[3]),
        "metrics_histogram" => Some(&DATASOURCES[4]),
        "metrics_exponential_histogram" => Some(&DATASOURCES[5]),
        "session_replays" => Some(&DATASOURCES[6]),
        "session_replay_events" => Some(&DATASOURCES[7]),
        "session_events" => Some(&DATASOURCES[8]),
        _ => None,
    }
}

