import { migration_0001_initial } from "./0001_initial"

export interface ClickHouseMigration {
	readonly version: number
	readonly description: string
	readonly statements: ReadonlyArray<string>
}

/**
 * Ordered list of every ClickHouse schema migration.
 *
 * The first entry is always the snapshot of the current schema (regenerated by
 * `bun run clickhouse:schema`). Subsequent entries are hand-authored deltas —
 * each one's `statements` should be the minimal set of `ALTER TABLE`,
 * `MATERIALIZE COLUMN`, or `CREATE MATERIALIZED VIEW` calls that take a server
 * from version N-1 to version N.
 *
 * A future improvement: a CI check that replays migrations 1..N against a fresh
 * ClickHouse and asserts the resulting `SHOW CREATE TABLE` matches running
 * just the latest snapshot. For now, snapshot tests on the DDL emitter plus
 * the live-DDL CI test catch the most common drift cases.
 */
export const migrations: ReadonlyArray<ClickHouseMigration> = [
	migration_0001_initial,
] as const
