// AUTO-GENERATED by atmn pull
// DO NOT EDIT MANUALLY

declare module "@useautumn/sdk" {
	// Features
	export const logs: Feature
	export const metrics: Feature
	export const traces: Feature

	// Plans
	export const free: Plan
	export const starter: Plan
	export const startup: Plan

	// Base types
	export type Feature = import("./autumn.config").Feature
	export type Plan = import("./autumn.config").Plan
}
