name: Tinybird - CI Workflow

on:
    workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.event.pull_request.number }}

permissions:
    contents: read

jobs:
    ci:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: "."
        services:
            tinybird:
                image: tinybirdco/tinybird-local:latest
                ports:
                    - 7181:7181
        steps:
            - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
            - name: Install Tinybird CLI
              run: curl https://tinybird.co | sh
            - name: Build project
              run: tb build
            - name: Test project
              run: tb test run
            - name: Deployment check
              env:
                  TINYBIRD_HOST: ${{ secrets.TINYBIRD_HOST }}
                  TINYBIRD_TOKEN: ${{ secrets.TINYBIRD_TOKEN }}
              run: tb --cloud --host "$TINYBIRD_HOST" --token "$TINYBIRD_TOKEN" deploy --check
